/* BIGWAVE3 ??i18n translations  (ko / en / ja / zh) */
const T = {
  ko: {
    /* NAV */
    'nav-overview':'媛쒖슂','nav-ir':'IR ?먮즺??,
    'nav-cosback':'肄붿뒪諛?,'nav-dreward':'?ν꽣由ъ썙??,'nav-member':'?뺥쉶??,
    'nav-compare':'?쒗깮鍮꾧탳','nav-media':'誘몃뵒??,'nav-cta':'Contact',
    'nav-sub-cos1':'COSBACK ?뚭컻','nav-sub-cos2':'酉고떚 ?먯궛 猷⑦봽','nav-sub-cos3':'?쇱꽦移대뱶 iD VITA',
    'nav-sub-dr1':'Dr.Reward ?뚭컻','nav-sub-dr2':'?쇱꽦?붿옱 蹂댄뿕',
    'nav-sub-mem1':'Great Beauty 硫ㅻ쾭??,'nav-sub-media2':'誘몃뵒??蹂대룄',
    /* HERO */
    'hero-badge':'?멸퀎 理쒖큹 CosTechMed 酉고떚??뚰겕 ?앺깭怨?,
    'hero-h1':'?뚮퉬媛 ?먯궛???섎뒗<br><em>K-酉고떚??誘몃옒</em>',
    'hero-sub':'?붿옣???뚮퉬媛 <strong>罹먯떆諛?/strong>???섍퀬,<br>?쒖닠 由ъ썙?쒓? ?섍퀬, <strong>?덉떖 蹂댄뿕</strong>???⑸땲??<br>BIGWAVE3??肄붿뒪諛깃낵 ?ν꽣 由ъ썙?쒕? ?곌껐??br>?뚮퉬媛 ?먯궛???섎뒗 K-酉고떚 ?앺깭怨꾨? 留뚮벊?덈떎.',
    'hero-btn1':'?뺥쉶???쒗깮 蹂닿린 ??,'hero-btn2':'肄붿뒪諛??ㅻ윭蹂닿린','hero-btn3':'?ν꽣 由ъ썙???뚯븘蹂닿린',
    'hero-plbl':'?뚰듃?덉떗',
    /* MARQUEE */
    'marquee':'COSBACK <span class="mstar">??/span> 理쒕? 10% 罹먯떆諛?<span class="mstar">??/span> Dr. Reward <span class="mstar">??/span> 蹂묒썝 1,000媛? <span class="mstar">??/span> Samsung Card iD VITA <span class="mstar">??/span> Samsung Fire 酉고떚耳?대낫??<span class="mstar">??/span> 103媛쒓뎅 湲濡쒕쾶 <span class="mstar">??/span> 2032 ?뚯썝 紐⑺몴 600留?紐?<span class="mstar">??/span> CosTechMed Platform <span class="mstar">??/span>',
    /* METRICS */
    'sec-metrics-h':'?쒕늿??蹂대뒗 BIGWAVE3 <em>?듭떖 吏??/em>',
    'mc1-lbl':'蹂몄씤 援щℓ 罹먯떆諛?,'mc1-desc':'肄붿뒪諛??낆젏 釉뚮옖??援щℓ ??理쒕? ?곷┰',
    'mc2-lbl':'移쒓뎄 異붿쿇 臾댄븳 罹먯떆諛?,'mc2-desc':'?쇱꽦 iD VITA移대뱶 寃곗젣湲덉븸 湲곗?',
    'mc3-lbl':'?곌컙 Great Beauty ?ㅽ듃','mc3-desc':'?뺥쉶??媛?????쒓났?섎뒗 ?곌컙 ?쒗깮 ?곷떦??,
    'mc4-lbl':'5???꾩쟻 ?뺥쉶??媛移?,'mc4-desc':'?뺥쉶???좎? ???꾩쟻 ?쒗깮 異붿궛',
    'mc5-lbl':'?뚰듃??蹂묒썝 ?ㅽ듃?뚰겕','mc5-desc':'?쇰?怨셋룹꽦?뺤쇅怨?500媛?+ 移섍낵쨌?ъ꽦?섏썝 500媛?,
    'mc6-lbl':'湲濡쒕쾶 Language Support','mc6-desc':'2032 ?뚯썝 紐⑺몴 600留?紐?,
    /* CTM */
    'sec-ctm-h':'CosTechMed <em>?꾪궎?띿쿂</em>',
    'sec-ctm-lead':'Cosmetics 횞 Technology 횞 Medical ??br>?뚮퉬瑜??먯궛?쇰줈 ?꾪솚?섎뒗 ?멸퀎 理쒖큹 ?앺깭怨?,
    'ctm-cos-h':'?쇱긽 ?뚮퉬 ?뚮옯??,'ctm-cos-p':'?붿옣?? 嫄닿컯?앺뭹, ?⑥뀡, ?ы뻾 ??怨좉컼???쇱긽 ?쇱씠?꾩뒪????뚮퉬瑜?肄붿뒪諛??뚮옯?쇱뿉???듯빀 愿由ы빀?덈떎.',
    'ctm-cos-t1':'?붿옣??,'ctm-cos-t2':'嫄닿컯?앺뭹','ctm-cos-t3':'?⑥뀡쨌?ы뻾',
    'ctm-tech-h':'?붿????곌껐 ?덉씠??,'ctm-tech-p':'QR ?몄쬆, ???곕룞, 罹먯떆諛? 由ъ썙?? 蹂댄뿕, 寃곗젣 湲곗닠 ?명봽?쇰줈 ?뚮퉬? ?쒗깮???ㅼ떆媛??곌껐?⑸땲??',
    'ctm-tech-t1':'QR쨌??,'ctm-tech-t2':'罹먯떆諛굿룸━?뚮뱶','ctm-tech-t3':'寃곗젣 ?곕룞',
    'ctm-med-h':'酉고떚 ?먯궛??,'ctm-med-p':'蹂묒썝 ?뺣낫 ?먯깋, ?쒖닠 由ъ썙???щ젅?? ?쇱꽦?붿옱 ?덉떖蹂댄뿕 ?곕룞?쇰줈 ?뚮퉬媛 酉고떚 ?먯궛???⑸땲??',
    'ctm-med-t1':'蹂묒썝 ?뺣낫','ctm-med-t2':'?쒖닠 由ъ썙??,'ctm-med-t3':'?덉떖 蹂댄뿕',
    /* COSBACK */
    'sec-cos-h':'COSBACK<br><em>?댁빱癒몄뒪 ?뚮옯??/em>',
    'sec-cos-lead':'?쇳븨?좎닔濡??꾧툑???뚯븘?ㅻ뒗 ?깃낵 湲곕컲 ?댁빱癒몄뒪 ??br>罹먯떆諛깃낵 ?ν꽣 由ъ썙?쒓? ?곌껐?⑸땲??',
    'cof1-lbl':'蹂몄씤 援щℓ 罹먯떆諛?,'cof1-desc':'肄붿뒪諛??낆젏 釉뚮옖?쒖뿉??br>援щℓ ??理쒕? 10% ?꾧툑???곷┰',
    'cof2-lbl':'移쒓뎄 異붿쿇 臾댄븳 罹먯떆諛?,'cof2-desc':'異붿쿇 留곹겕濡?媛?낇븳<br>移쒓뎄媛 援щℓ???뚮쭏??br>吏???곷┰',
    'cof3-lbl':'?ν꽣 由ъ썙???곕룞','cof3-desc':'?쒗뭹 QR ?ㅼ틪 ??酉고떚<br>?쒖닠 由ъ썙???먮룞 ?곕룞',
    'cof4-lbl':'移댄뀒怨좊━','cof4-desc':'Beauty 쨌 Health 쨌 Fashion 쨌 Travel<br>??移댄뀒怨좊━',
    'cos-brands-lbl':'?낆젏 釉뚮옖???덉떆',
    'cos-float1':'?대쾲??罹먯떆諛??곷┰','cos-float2':'Dr. Reward 由ъ썙???곕룞',
    /* LOOP */
    'sec-loop-h':'酉고떚 <em>?먯궛 猷⑦봽</em> 怨좉컼 ?ъ젙',
    'sec-loop-lead':'From First Purchase to Infinite Cashback ??br>10-Step Beauty Asset Journey',
    'ls1':'??肄붿뒪諛?br>媛??,'ls2':'???뺥쉶??br>?쒗깮 ?쒖꽦??,'ls3':'??釉뚮옖??br>?곹뭹 援щℓ','ls4':'??罹먯떆諛?br>?곷┰','ls5':'??QR<br>?ㅼ틪',
    'ls6':'???ν꽣由ъ썙??br>?곷┰','ls7':'??蹂묒썝<br>?뺣낫 ?먯깋','ls8':'???쒖닠 ??br>由ъ썙???쒖슜','ls9':'???쇱꽦?붿옱<br>蹂댄뿕 ?곕룞','ls10':'??移쒓뎄異붿쿇<br>臾댄븳 罹먯떆諛?,
    'loop-b1':'肄붿뒪諛?罹먯떆諛?,'loop-b2':'?ν꽣 由ъ썙???щ젅??,'loop-b3':'?쇱꽦?붿옱 ?덉떖蹂댄뿕','loop-b4':'臾댄븳 罹먯떆諛?猷⑦떞',
    /* SAMSUNG CARD */
    'sec-sc-h':'?쇱꽦移대뱶 <em>iD VITA</em><br>?묐젰 湲덉쑖 猷⑦떞',
    'sec-sc-lead':'COSBACK 횞 Samsung Card iD VITA ??br>怨좉컼???ㅼ뒪濡??좏깮?섎뒗 ?ㅻ쭏?명븳 ?뺥쉶???꾪솚 ?붿쭊',
    'scf1-t':'蹂묒썝쨌?쎄뎅 ?쒗깮','scf1-d':'?뚰듃??蹂묒썝 諛??쎄뎅?먯꽌 20% ?좎씤 ?쒗깮 ?쒓났',
    'scf2-t':'?앺솢 ?곸뿭 ?쒗깮','scf2-d':'?쇱긽 ?앺솢 ?꾨컲??移대뱶 ?쒗깮',
    'scf3-t':'理쒕? 15% 臾댄븳 罹먯떆諛?,'scf3-d':'?쇱꽦 iD VITA移대뱶 寃곗젣湲덉븸 湲곗?',
    'scf4-t':'?쇱꽦?붿옱 蹂댄뿕 ?곕룞','scf4-d':'酉고떚耳???덉떖蹂댄뿕 ?깆뿉???ㅼ떆媛??뺤씤',
    'paths-lbl':'?뺥쉶??媛??寃쎈줈',
    'piA-tag':'Path A','piA-t':'?꾧툑 ?⑸???,'piA-d':'肄붿뒪諛??고쉶鍮???50,000 吏곸젒 ?⑸?',
    'piB-tag':'Path B 狩?Recommended','piB-t':'iD VITA 媛?낇삎','piB-d':'肄붿뒪諛??뺥쉶???고쉶鍮?臾대즺',
    'sc-float1-t':'移쒓뎄 異붿쿇 罹먯떆諛?,'sc-float1-s':'?쇱꽦 iD VITA移대뱶 寃곗젣 ??,
    'sc-float2-t':'酉고떚耳??蹂댄뿕','sc-float2-s':'Samsung Fire ?곕룞 ?꾨즺',
    /* DR REWARD */
    'sec-dr-h':'Dr. Reward<br><em>Beauty & Wellness Platform</em>',
    'drf1-t':'由ъ썙???뺤씤','drf1-d':'肄붿뒪諛?援щℓ쨌QR ?몄쬆쨌?뺥쉶???쒗깮쨌移쒓뎄 異붿쿇?쇰줈 ?볦씤 由ъ썙?쒕? ?깆뿉???쒕늿???뺤씤',
    'drf2-t':'蹂묒썝 ?뺣낫 ?먯깋','drf2-d':'?쇰?怨셋룹꽦?뺤쇅怨셋룻뿤?는룸꽕?셋룹뿉?ㅽ뀒?굿룻븘?쇳뀒??吏??퀎 蹂묒썝 ?뺣낫 ?먯쑀 ?먯깋 - 怨좉컼 Viewing ?좏깮',
    'drf3-t':'?쒖닠 ???щ젅???쒖슜','drf3-d':'蹂댁쑀 由ъ썙?쒕? ?쒖닠 ??寃곗젣 ?④퀎?먯꽌 ?щ젅?㏃쿂???쒖슜',
    'drf4-t':'?쇱꽦?붿옱 蹂댄뿕 ?곕룞','drf4-d':'?깆뿉???쇱꽦?붿옱 酉고떚耳???덉떖蹂댄뿕??諛붾줈 媛?낇븷 ???덉쑝硫? ?쒖닠 ??遺?묒슜쨌?꾩쑀利?由ъ뒪?щ? ?덉쟾?섍쾶 蹂댁옣諛쏆쓣 ???덉뒿?덈떎',
    'dr-float1-s':'由ъ썙???곷┰ ?꾨즺','dr-float2-s':'?뚰듃??蹂묒썝 ?ㅽ듃?뚰겕',
    /* GREAT BEAUTY */
    'sec-gb-h':'Great Beauty <em>?뺥쉶??/em> 硫ㅻ쾭???쒗깮',
    'sec-gb-lead':'Annual Value ??00,000 ??br>Premium Beauty Fintech Membership',
    'gb-badge':'??50留뚯썝 ?곷떦',
    'gbc1-t':'?ν꽣 由ъ썙???쒖닠 由ъ썙??,'gbc1-v':'??00,000 ?곷떦','gbc1-d':'?쇰?怨셋룹꽦?뺤쇅怨??뚰듃??蹂묒썝 ?쒖슜 媛?ν븳 酉고떚 由ъ썙???щ젅??,
    'gbc2-t':'?쇱꽦?붿옱 酉고떚耳???덉떖蹂댄뿕','gbc2-v':'1??臾댁긽 蹂댁옣','gbc2-d':'?쒖닠 ??遺?묒슜쨌?꾩쑀利?由ъ뒪???덉쟾留? BIGWAVE3媛 蹂댄뿕猷?吏??,
    'gbc3-t':'?꾨━誘몄뾼 ?붾쭏 肄붿뒪硫뷀떛 ?명듃','gbc3-v':'??50,000 ?곷떦','gbc3-d':'?쒖닠 ?꾪썑 ?쇰? 而⑤뵒??愿由??덉????쒗뭹. 怨좉컼 ?좏깮???쒗깮',
    'gbc4-t':'臾댄븳 罹먯떆諛?猷⑦떞','gbc4-v':'臾댁젣???곷┰','gbc4-d':'移쒓뎄 異붿쿇怨?肄붿뒪諛?援щℓ瑜??듯븳 吏?띿쟻???꾧툑??罹먯떆諛??곷┰',
    'gj-t':'泥섏쓬?먮뒗 臾대즺濡??쒖옉?섏꽭??,'gj-s':'?섏?留?Great Beauty ?쒗깮? ?뺥쉶?먯뿉寃뚮쭔 ?대┰?덈떎',
    'gjpA':'A?????고쉶鍮???50,000 ?⑸???,'gjpB':'B????iD VITA 媛?낇삎 : ?고쉶鍮?臾대즺 狩?,
    /* COMPARE */
    'sec-cmp-h':'?쇰컲 ?뚯썝 vs <em>?뺥쉶??/em> ?쒗깮 鍮꾧탳',
    'ch-gen-lbl':'General Member','ch-gen-t':'?쇰컲 ?뚯썝','ch-gen-sub':'臾대즺 媛??,
    'ch-prem-lbl':'Premium Member','ch-prem-t':'?뺥쉶??,'ch-prem-sub':'?고쉶鍮??먮뒗 ?곌퀎移대뱶 ?깅줉',
    'cr1':'?썚 肄붿뒪諛?援щℓ','cr2':'?뮥 蹂몄씤 罹먯떆諛?,'cr3':'?뫁 移쒓뎄 異붿쿇 罹먯떆諛?,
    'cr4':'?룯 ?ν꽣 由ъ썙??,'cr5':'?럞 Great Beauty ?ㅽ듃','cr6':'?썳 ?쇱꽦?붿옱 蹂댄뿕','cr7':'?뵕 異붿쿇 肄붾뱶',
    'gen-v1':'媛??,'gen-v2':'湲곕낯 ?쒗깮','gen-v3':'?쒗븳??,'gen-v4':'?쇰? ?뺣낫留?,'gen-v5':'誘몄젣怨?,'gen-v6':'誘몄젣怨?,'gen-v7':'?쇰컲 異붿쿇',
    'gen-foot':'泥댄뿕 怨좉컼 쨌 ?몃옒???붿쭊',
    'prem-v1':'理쒕? ?쒗깮 ??,'prem-v2':'理쒕? 10% ??,'prem-v3':'?쇱꽦移대뱶 理쒕? 15% 臾댄븳 ??,
    'prem-v4':'?쒖닠 由ъ썙???곷┰쨌?쒖슜 ??,'prem-v5':'??50留뚯썝 ?곷떦 ??,'prem-v6':'?곕룞 媛????,'prem-v7':'?ㅻ꼫??異붿쿇 肄붾뱶 ??,
    'prem-foot':'?듭떖 ?쒗깮 怨좉컼 쨌 ?섏씡 ?붿쭊','prem-cta':'?뺥쉶???쒗깮 ?쒖꽦?뷀븯湲???,
    /* DR TV */
    'sec-tv-h':'Dr. Reward TV <em>誘몃뵒???쇳꽣</em>',
    'sec-tv-lead':'3遺꾩씠硫??댄빐?섎뒗 酉고떚??뚰겕 ??肄붿뒪諛굿룸떏??由ъ썙?쑣룸낫?샕룻닾?먭퉴吏',
    'tv-main-title':'?뚮퉬媛 ?먯궛???섎뒗 湲곗쟻,<br>CosTechMed???쒖옉',
    'tv-it1':'?쇱꽦?붿옱 蹂댄뿕 ?덈궡','tv-it2':'?쇱꽦移대뱶 iD VITA ?덈궡',
    'tv-it3':'怨좉컼 ?명꽣酉???酉고떚 ?뚮퉬媛 ?먯궛????寃쏀뿕',
    'tv-it4':'?쇰?怨??먯옣 ?명꽣酉????섏궗媛 蹂대뒗 酉고떚 由ъ썙??,
    'tv-it5':'?ъ옄???명꽣酉???酉고떚??뚰겕 ?덈줈???쒖옣',
    'tv-more':'?꾩껜 ?곸긽 蹂닿린 ??,
    /* FINAL CTA */
    'cta-h2':'BIGWAVE3 ?앺깭怨꾩뿉<br><em>吏湲??⑸쪟?섏꽭??/em>',
    'cta-p':'怨좉컼, 釉뚮옖?? 蹂묒썝, ?ъ옄??紐⑤몢瑜??꾪븳 ?곌껐??br>?ш린???쒖옉?⑸땲??,
    'ctac1-t':'怨좉컼','ctac1-d':'Great Beauty ?뺥쉶?먯씠 ?섏뼱<br>罹먯떆諛? ?쒖닠 由ъ썙?? ?덉떖 蹂댄뿕 ?쒗깮???쒖옉?섏꽭??,'ctac1-btn':'?뺥쉶??媛?낇븯湲???,
    'ctac2-t':'釉뚮옖?쒖궗','ctac2-d':'愿묎퀬鍮??놁씠 ?깃낵 湲곕컲?쇰줈<br>怨좉컼?먭쾶 ?쒗깮???뚯븘媛??肄붿뒪諛??낆젏???쒖옉?섏꽭??,'ctac2-btn':'釉뚮옖???낆젏 ?좎껌 ??,
    'ctac3-t':'?뚰듃??蹂묒썝','ctac3-d':'怨좉???酉고떚 怨좉컼怨??곌껐?섎뒗<br>?ν꽣 由ъ썙???뚰듃??蹂묒썝???섏꽭??,'ctac3-btn':'蹂묒썝 ?낆젏 ?좎껌 ??,
    'ctac4-t':'?ъ옄??,'ctac4-d':'CosTechMed ?앺깭怨꾩쓽 ?깆옣?깃낵<br>?ъ옄 湲고쉶瑜??뺤씤?섏꽭??,'ctac4-btn':'IR ?먮즺 ?붿껌 ??,
    'cta-bottom-p':'?뚮퉬?????댁긽 ?щ씪吏??鍮꾩슜???꾨떃?덈떎',
    /* FOOTER */
    'ft-brand-p':'?뚮퉬媛 ?먯궛???섎뒗 ?멸퀎 理쒖큹??CosTechMed 酉고떚??뚰겕 ?앺깭怨? COSBACK怨??ν꽣 由ъ썙?? ?쇱꽦移대뱶쨌?쇱꽦?붿옱媛 ?④퍡?⑸땲??',
    'ft-l1':'肄붿뒪諛?(COSBACK)','ft-l2':'?ν꽣 由ъ썙??,'ft-l3':'Great Beauty ?뺥쉶??,'ft-l4':'Dr. Reward TV',
    'ft-l5':'釉뚮옖???낆젏 ?좎껌','ft-l6':'蹂묒썝 ?낆젏 ?좎껌','ft-l7':'?쇱꽦移대뱶 ?쒗쑕','ft-l8':'?쇱꽦?붿옱 ?곕룞',
    'ft-l9':'?뚯궗 ?뚭컻','ft-l10':'IR ?먮즺 ?붿껌','ft-l11':'?댁뒪猷?,'ft-l12':'?댁슜?쎄? 쨌 媛쒖씤?뺣낫泥섎━諛⑹묠',
    /* ABOUT PAGE */
    'about-nav-ir':'IR ?먮즺??,
    'about-nav-back':'?덉쑝濡??뚯븘媛湲?,
    'about-hero-label':'Company Introduction',
    'about-hero-h1':'酉고떚 ?뚮퉬瑜?<em>?먯궛?쇰줈</em><br>?곌껐?섎뒗 ?뚮옯??,
    'about-hero-sub':'K-酉고떚, ?ъ뒪耳?? ?댁빱癒몄뒪, 由ъ썙???쒖뒪?쒖쓣 寃고빀??br>李⑥꽭? 酉고떚??뚰겕 ?뚮옯??湲곗뾽',
    'about-ov-label':'Company Overview','about-ov-title':'?뚯궗 <em>媛쒖슂</em>',
    'about-ov-r1k':'?뚯궗紐?,'about-ov-r2k':'??쒖옄','about-ov-r2v':'?쒕???,
    'about-ov-r3k':'李쎈┰??,'about-ov-r3v':'2024??11??14??,
    'about-ov-r4k':'二쇱슂 ?ъ뾽 遺꾩빞','about-ov-r4v':'?붿옣???꾨ℓ?? ?뚰봽?몄썾??諛??쒖뒪??媛쒕컻, ?뺣낫?듭떊?? ?쏀뭹 愿??寃쎌쁺 而⑥꽕?낆뾽',
    'about-ov-r5k':'二쇱슂 湲곗닠','about-ov-r5v':'酉고떚, ?ъ뒪耳?? ?댁빱癒몄뒪, 由ъ썙???쒖뒪?쒖쓣 寃고빀??李⑥꽭? 酉고떚??뚰겕 ?뚮옯??,
    'about-ov-r6k':'?꾪솕踰덊샇','about-ov-r7k':'?대찓??,
    'about-svc-label':'Core Services','about-svc-title':'?듭떖 <em>?쒕퉬??/em>',
    'about-svc1-t':'肄붿뒪諛?,'about-svc1-d':'K-酉고떚, ?ъ뒪耳?? ?⑥뀡, ?ы뻾, ?쇱씠?꾩뒪????곹뭹??湲곕컲?쇰줈 ???댁빱癒몄뒪 ?뚮옯?? 援щℓ ?쒕룞怨??쒗쑕 ?쒗깮??湲곕컲?쇰줈 ?ㅼ뼇??由ъ썙?쒕? ?곷┰?????덉뒿?덈떎.',
    'about-svc2-t':'?ν꽣 由ъ썙??,'about-svc2-d':'蹂묒썝怨??ㅼ뼱, ?ㅼ씪, ?꾨씪?뚯뒪 ???곕땲???뺣낫瑜??쒓났?섍퀬 由ъ썙???곷┰??寃고빀??紐⑤컮???뚮옯?? 怨좉컼怨?釉뚮옖??媛꾩쓽 ?묒젏???뺣??⑸땲??',
    'about-svc3-t':'?섏씠釉뚮━???앺깭怨?,'about-svc3-d':'COSBACK怨?Doctor Reward瑜?以묒떖?쇰줈 K-酉고떚, 蹂묒썝쨌?곕땲???뺣낫, 怨좉컼 由ъ썙?? ?쒗쑕 湲덉쑖쨌蹂댄뿕 ?쒕퉬?ㅻ? ?곌껐?섎뒗 ?섏씠釉뚮━???뚮옯??援ъ“.',
    'about-str-label':'Core Strengths','about-str-title':'?듭떖 <em>媛뺤젏</em>',
    'about-str-sub':'酉고떚, ?ъ뒪耳?? ??뚰겕瑜??곌껐?섎뒗 BIGWAVE3??李⑤퀎?붾맂 寃쎌웳?μ쑝濡?吏??媛?ν븳 ?깆옣??留뚮뱾?닿컩?덈떎.',
    'about-str1-h':'?댁빱癒몄뒪? 蹂묒썝?뺣낫 ?뚮옯?쇱쓽 ?댁쨷 援ъ“','about-str1-p':'COSBACK? ?쒗뭹 援щℓ? 由ъ썙???곷┰??以묒떖 ?뚮옯?쇱씠硫? Doctor Reward??蹂묒썝 ?뺣낫 ?쒓났怨??곕땲???쒗깮???묒젏 ?뚮옯?쇱엯?덈떎. ???뚮옯?쇱? 媛곴컖 ?낅┰?곸씤 湲곕뒫??媛뽰텛硫댁꽌?? 怨좉컼 寃쏀뿕 ?덉뿉?쒕뒗 ?섎굹???곌껐??酉고떚??뚰겕 ?앺깭怨꾨줈 ?묐룞?⑸땲??',
    'about-str2-h':'K-酉고떚 釉뚮옖???좏넻 湲곕컲','about-str2-p':'援?궡 ?꾨━誘몄뾼 K-酉고떚 釉뚮옖?쒖????좏넻 諛??뚮옯???곕룞???듯빐 ?쒗뭹 湲곕컲??怨좉컼 ?좎엯 援ъ“瑜?媛뺥솕?섍퀬 ?덉뒿?덈떎. ?⑥닚 愿묎퀬 以묒떖???꾨땲?? ?ㅼ젣 ?쒗뭹 援щℓ? ?ъ슜 寃쏀뿕???듯빐 ?뚮옯???뚯썝?쇰줈 ?꾪솚?섎뒗 援ъ“瑜?吏?ν빀?덈떎.',
    'about-str3-h':'由ъ썙???쒖뒪??愿??吏?앹옱??湲곕컲','about-str3-p':'?붿옣??援щℓ???곕Ⅸ 由ъ썙???곷┰ 諛??ъ슜 ?쒖뒪?쒓낵 愿?⑤맂 ?뱁뿀寃곗젙 ?댁슜??湲곕컲?쇰줈 ?ъ뾽紐⑤뜽??怨좊룄?붾릺怨??덉뒿?덈떎. 援щℓ ?됱쐞? 由ъ썙???ъ슜 援ъ“瑜??쒖뒪?쒗솕???뚮옯??湲곗닠 ?먯궛?쇰줈 ?뺤옣?⑸땲??',
    'about-ach-label':'Key Achievement','about-ach-title':'二쇱슂 <em>?ㅼ쟻</em>',
    'about-ach-sub':'BIGWAVE3???낆옄?곸씤 湲곗닠?κ낵<br>吏?앹옱??湲곕컲?쇰줈 李⑤퀎?붾맂 媛移섎? 留뚮뱾?닿컩?덈떎.',
    'about-pat-h':'?뱁뿀寃곗젙 湲곕컲 湲곗닠 ?먯궛',
    'about-pat-p':'?뚯궗???듭떖 ?ъ뾽紐⑤뜽怨??곌껐?섎뒗 <strong>?붿옣??援щℓ???곕Ⅸ 由ъ썙???곷┰ 諛??ъ슜 ?쒖뒪??/strong>, 洹몃━怨??대떦 ?쒖뒪?쒖뿉???섑뻾?섎뒗 由ъ썙???곷┰ 諛??ъ슜 諛⑸쾿??????뱁뿀寃곗젙???뺤씤?섏뿀?듬땲??',
    'about-pat-note':'?대뒗 ?ν썑 COSBACK怨?Doctor Reward??br>由ъ썙??援ъ“瑜?李⑤퀎?뷀븯??湲곗닠??洹쇨굅濡??쒖슜?????덉뒿?덈떎.',
    'about-tag1-t':'吏?앹옱??湲곕컲','about-tag1-s':'?낆옄??湲곗닠 ?먯궛 ?뺣낫',
    'about-tag2-t':'?ъ뾽 ?곌퀎??媛뺥솕','about-tag2-s':'?듭떖 ?ъ뾽紐⑤뜽怨?吏곸젒 ?곌껐',
    'about-tag3-t':'誘몃옒 媛移?李쎌텧','about-tag3-s':'吏??媛?ν븳 寃쎌웳 ?곗쐞',
    'about-vis-label':'Vision','about-vis-title':'鍮낆썾?대툕3??<em>鍮꾩쟾</em>',
    'about-vis-quote':'<span class="vq-mark">"</span>K-酉고떚 援щℓ 寃쏀뿕??<em>由ъ썙??湲덉쑖 寃쏀뿕?쇰줈 ?뺤옣</em>?섍퀬,<br>蹂묒썝 ?뺣낫? ?곕땲???쒗깮???곌껐?섎뒗<br>湲濡쒕쾶 酉고떚??뚰겕 ?뚮옯??span class="vq-mark">"</span>',
    'about-vis-desc':'鍮낆썾?대툕3??怨좉컼???⑥닚???쒗뭹??援щℓ?섎뒗 寃껋쓣 ?섏뼱, 援щℓ 怨쇱젙?먯꽌 ?쒗깮???곷┰?섍퀬,<br>?곷┰???쒗깮???ㅼ떆 ?곕땲?ㅼ? 蹂묒썝 ?뺣낫 寃쏀뿕?쇰줈 ?곌껐?섎뒗 ?덈줈???뚮퉬 援ъ“瑜?留뚮뱾怨좎옄 ?⑸땲??',
    'about-vis-divider':'鍮낆썾?대툕3??酉고떚 ?곗뾽??援щℓ 寃쏀뿕??<strong>?곗씠?곗? 由ъ썙??以묒떖?쇰줈 ?ъ꽕怨?/strong>?섍퀬 ?덉뒿?덈떎.',
    'about-closing-p1':'<strong>COSBACK</strong>? K-酉고떚 ?댁빱癒몄뒪???뺤옣?깆쓣 ?대떦?섍퀬,<br><strong>Doctor Reward</strong>??蹂묒썝 ?뺣낫? ?곕땲??由ъ썙??寃쏀뿕???곌껐?⑸땲??',
    'about-closing-p2':'?욎쑝濡쒕룄 K-酉고떚, ?ъ뒪耳?? ??뚰겕, 湲濡쒕쾶 ?좏넻???곌껐?섎뒗 ?곸떊?곸씤 ?뚮옯??湲곗뾽?쇰줈 ?깆옣???섍?寃좎뒿?덈떎.',
  },

  en: {
    'nav-overview':'Overview','nav-ir':'IR Room',
    'nav-cosback':'COSBACK','nav-dreward':'Dr. Reward','nav-member':'Premium',
    'nav-compare':'Compare','nav-media':'Media','nav-cta':'Request IR',
    'nav-sub-cos1':'About COSBACK','nav-sub-cos2':'Beauty Asset Loop','nav-sub-cos3':'Samsung Card iD VITA',
    'nav-sub-dr1':'About Dr.Reward','nav-sub-dr2':'Samsung Fire Insurance',
    'nav-sub-mem1':'Great Beauty Membership','nav-sub-media2':'Media Coverage',
    'hero-badge':'World\'s First CosTechMed Beauty Fintech Ecosystem',
    'hero-h1':'Where Spending Becomes<br><em>The Future of K-Beauty</em>',
    'hero-sub':'Cosmetics spending becomes <strong>cashback</strong>,<br>treatment rewards, and <strong>peace-of-mind insurance</strong>.<br>BIGWAVE3 connects COSBACK &amp; Dr. Reward<br>to build a K-Beauty ecosystem where spending becomes assets.',
    'hero-btn1':'See Premium Benefits ??,'hero-btn2':'Explore COSBACK','hero-btn3':'Learn Dr. Reward',
    'hero-plbl':'Partnership',
    'marquee':'COSBACK <span class="mstar">??/span> Up to 10% Cashback <span class="mstar">??/span> Dr. Reward <span class="mstar">??/span> 1,000+ Clinics <span class="mstar">??/span> Samsung Card iD VITA <span class="mstar">??/span> Samsung Fire Beauty Insurance <span class="mstar">??/span> 103 Countries <span class="mstar">??/span> 6M Members Goal by 2032 <span class="mstar">??/span> CosTechMed Platform <span class="mstar">??/span>',
    'sec-metrics-h':'BIGWAVE3 <em>Key Metrics</em> at a Glance',
    'mc1-lbl':'Personal Purchase Cashback','mc1-desc':'Up to 10% on every COSBACK brand purchase',
    'mc2-lbl':'Infinite Friend Referral','mc2-desc':'Earn every time your referred friend shops with Samsung Card',
    'mc3-lbl':'Annual Great Beauty Kit','mc3-desc':'Estimated annual benefit value for premium members',
    'mc4-lbl':'5-Year Member Value','mc4-desc':'Cumulative estimated benefit over 5 years of membership',
    'mc5-lbl':'Partner Clinic Network','mc5-desc':'500 dermatology & plastic surgery + 500 dental & women\'s clinics',
    'mc6-lbl':'Global Language Support','mc6-desc':'Target 6M members by 2032',
    'sec-ctm-h':'CosTechMed <em>Architecture</em>',
    'sec-ctm-lead':'Cosmetics 횞 Technology 횞 Medical ??The world\'s first ecosystem turning spending into assets',
    'ctm-cos-h':'Everyday Spending Platform','ctm-cos-p':'Manage all lifestyle spending ??cosmetics, health, fashion, travel ??in one unified COSBACK platform.',
    'ctm-cos-t1':'Cosmetics','ctm-cos-t2':'Health Food','ctm-cos-t3':'Fashion 쨌 Travel',
    'ctm-tech-h':'Digital Connection Layer','ctm-tech-p':'QR, app integration, cashback, rewards, insurance, and payment infrastructure ??connecting spending to benefits in real time.',
    'ctm-tech-t1':'QR 쨌 App','ctm-tech-t2':'Cashback 쨌 Rewards','ctm-tech-t3':'Payment Link',
    'ctm-med-h':'Beauty Asset Return','ctm-med-p':'Clinic discovery, treatment reward credits, and Samsung Fire insurance integration turn spending into beauty assets.',
    'ctm-med-t1':'Clinic Info','ctm-med-t2':'Treatment Rewards','ctm-med-t3':'Peace-of-Mind Insurance',
    'sec-cos-h':'COSBACK<br><em>E-Commerce Platform</em>',
    'sec-cos-lead':'Performance-based e-commerce where every purchase pays you back ??cashback meets Dr. Reward.',
    'cof1-lbl':'Personal Cashback','cof1-desc':'Up to 10% cash reward on every COSBACK brand purchase',
    'cof2-lbl':'Infinite Friend Referral','cof2-desc':'Earn every time a referred friend makes a purchase',
    'cof3-lbl':'Dr. Reward Integration','cof3-desc':'Scan product QR to automatically earn beauty treatment rewards',
    'cof4-lbl':'Categories','cof4-desc':'Beauty 쨌 Health 쨌 Fashion 쨌 Travel ??all categories',
    'cos-brands-lbl':'Partner Brand Examples',
    'cos-float1':'Cashback this month','cos-float2':'Dr. Reward Connected',
    'sec-loop-h':'Beauty <em>Asset Loop</em> Customer Journey',
    'sec-loop-lead':'From First Purchase to Infinite Cashback ??br>10-Step Beauty Asset Journey',
    'ls1':'??Join<br>COSBACK','ls2':'??Activate<br>Premium','ls3':'??Buy<br>Brands','ls4':'??Earn<br>Cashback','ls5':'??Scan<br>QR',
    'ls6':'??Earn<br>Dr. Reward','ls7':'??Explore<br>Clinics','ls8':'??Use Reward<br>Post-Treatment','ls9':'??Samsung Fire<br>Insurance','ls10':'??Infinite<br>Friend Referral',
    'loop-b1':'COSBACK Cashback','loop-b2':'Dr. Reward Credit','loop-b3':'Samsung Fire Insurance','loop-b4':'Infinite Cashback Loop',
    'sec-sc-h':'Samsung Card <em>iD VITA</em><br>Partnership',
    'sec-sc-lead':'COSBACK 횞 Samsung Card iD VITA ??A smart premium membership engine chosen by customers themselves',
    'scf1-t':'Clinic & Pharmacy Benefits','scf1-d':'Special benefits at partner clinics and pharmacies',
    'scf2-t':'Everyday Life Benefits','scf2-d':'Card benefits across all areas of daily life',
    'scf3-t':'Up to 15% Infinite Cashback','scf3-d':'15% on friends\' purchases when paying with partner Samsung Card',
    'scf4-t':'Samsung Fire Integration','scf4-d':'Check beauty care insurance status in real time via app',
    'paths-lbl':'Premium Membership Paths',
    'piA-tag':'Path A','piA-t':'Direct Payment','piA-d':'Pay ??50,000 annual fee directly',
    'piB-tag':'Path B 狩?Recommended','piB-t':'iD VITA Voluntary Sign-up','piB-d':'Customer\'s own choice ??no pressure',
    'sc-float1-t':'Friend Referral Cashback','sc-float1-s':'Via partner Samsung Card',
    'sc-float2-t':'Beauty Care Insurance','sc-float2-s':'Samsung Fire linked',
    'sec-dr-h':'Dr. Reward<br><em>Mobile Platform</em>',
    'drf1-t':'Check Rewards','drf1-d':'See all rewards earned from purchases, QR scans, premium benefits, and referrals in one view',
    'drf2-t':'Explore Clinics','drf2-d':'Browse dermatology, plastic surgery, and treatment categories by region. Customer\'s free choice ??no forced recommendations',
    'drf3-t':'Use Credits Post-Treatment','drf3-d':'Apply accumulated rewards as credits at the payment stage after treatment',
    'drf4-t':'Insurance Status','drf4-d':'Check Samsung Fire beauty care insurance link status in real time',
    'dr-float1-s':'Reward earned','dr-float2-s':'Partner Clinic Network',
    'sec-gb-h':'Great Beauty <em>Premium</em> Membership Benefits',
    'sec-gb-lead':'Annual Value ??00,000 ??Premium Beauty Fintech Membership',
    'gb-badge':'??00K Annual Value',
    'gbc1-t':'Dr. Reward Treatment Credit','gbc1-v':'Worth ??00,000','gbc1-d':'Beauty reward credit usable at partner dermatology & plastic surgery clinics',
    'gbc2-t':'Samsung Fire Beauty Insurance','gbc2-v':'1 Year Free Coverage','gbc2-d':'Safety net for side effects after treatment. BIGWAVE3 covers the premium',
    'gbc3-t':'Premium Derma Cosmetic Set','gbc3-v':'Worth ??50,000','gbc3-d':'Home-care products for skin condition before and after treatment. Customer\'s choice',
    'gbc4-t':'Infinite Cashback Routine','gbc4-v':'Unlimited','gbc4-d':'Continuous cash-equivalent cashback via friend referrals and COSBACK purchases',
    'gj-t':'Start free today','gj-s':'But Great Beauty benefits are exclusive to premium members',
    'gjpA':'Path A ????50,000 Annual Fee','gjpB':'Path B ??iD VITA Voluntary 狩?,
    'sec-cmp-h':'General vs <em>Premium</em> Membership Comparison',
    'ch-gen-lbl':'General Member','ch-gen-t':'General','ch-gen-sub':'Free',
    'ch-prem-lbl':'Premium Member','ch-prem-t':'Premium','ch-prem-sub':'Annual fee or partner card',
    'cr1':'?썚 COSBACK Shopping','cr2':'?뮥 Personal Cashback','cr3':'?뫁 Friend Referral',
    'cr4':'?룯 Dr. Reward','cr5':'?럞 Great Beauty Kit','cr6':'?썳 Samsung Fire Insurance','cr7':'?뵕 Referral Code',
    'gen-v1':'Available','gen-v2':'Basic','gen-v3':'Limited','gen-v4':'Partial info','gen-v5':'Not included','gen-v6':'Not included','gen-v7':'Standard',
    'gen-foot':'Trial users 쨌 Traffic engine',
    'prem-v1':'Max benefits ??,'prem-v2':'Up to 10% ??,'prem-v3':'Samsung Card up to 15% infinite ??,
    'prem-v4':'Earn & use treatment rewards ??,'prem-v5':'??00K annual value ??,'prem-v6':'Linked ??,'prem-v7':'Ownership referral code ??,
    'prem-foot':'Core benefit users 쨌 Revenue engine','prem-cta':'Activate Premium Benefits ??,
    'sec-tv-h':'Dr. Reward TV <em>Media Center</em>',
    'sec-tv-lead':'Understand beauty fintech in 3 minutes ??COSBACK, Dr. Reward, insurance, investing',
    'tv-main-title':'The miracle of spending becoming assets ??br>The beginning of CosTechMed',
    'tv-it1':'Samsung Fire Insurance Guide','tv-it2':'Samsung Card iD VITA Guide',
    'tv-it3':'Customer Interview ??How spending became an asset','tv-it4':'Dermatologist Interview ??A doctor\'s view on beauty rewards',
    'tv-it5':'Investor Interview ??The new beauty fintech market',
    'tv-more':'View All Videos ??,
    'cta-h2':'Join the BIGWAVE3<br><em>Ecosystem Now</em>',
    'cta-p':'Connections for customers, brands, clinics, and investors all start here',
    'ctac1-t':'Customers','ctac1-d':'Become a Great Beauty premium member and start earning cashback, treatment rewards, and insurance','ctac1-btn':'Join Premium ??,
    'ctac2-t':'Brands','ctac2-d':'List on COSBACK ??performance-based benefits with no ad spend','ctac2-btn':'List Your Brand ??,
    'ctac3-t':'Clinics','ctac3-d':'Become a Dr. Reward partner clinic and connect with high-intent beauty customers','ctac3-btn':'Partner With Us ??,
    'ctac4-t':'Investors','ctac4-d':'Explore the growth potential and investment opportunity in the CosTechMed ecosystem','ctac4-btn':'Request IR Materials ??,
    'cta-bottom-p':'Spending is no longer a cost that disappears',
    'ft-brand-p':'The world\'s first CosTechMed beauty fintech ecosystem where spending becomes assets. With COSBACK, Dr. Reward, Samsung Card & Samsung Fire.',
    'ft-l1':'COSBACK','ft-l2':'Dr. Reward','ft-l3':'Great Beauty Premium','ft-l4':'Dr. Reward TV',
    'ft-l5':'Brand Listing','ft-l6':'Clinic Listing','ft-l7':'Samsung Card Partnership','ft-l8':'Samsung Fire Link',
    'ft-l9':'About Us','ft-l10':'IR Materials','ft-l11':'Newsroom','ft-l12':'Terms 쨌 Privacy Policy',
    /* ABOUT PAGE */
    'about-nav-ir':'IR Room',
    'about-nav-back':'Back to Home',
    'about-hero-label':'Company Introduction',
    'about-hero-h1':'The Platform That Turns<br><em>Beauty Spending into Assets</em>',
    'about-hero-sub':'A next-generation beauty fintech platform company<br>combining K-Beauty, healthcare, e-commerce, and rewards',
    'about-ov-label':'Company Overview','about-ov-title':'Company <em>Overview</em>',
    'about-ov-r1k':'Company Name','about-ov-r2k':'CEO','about-ov-r2v':'Seo Min-hee',
    'about-ov-r3k':'Founded','about-ov-r3v':'November 14, 2024',
    'about-ov-r4k':'Business Areas','about-ov-r4v':'Cosmetics wholesale, software & system development, IT services, pharmaceutical management consulting',
    'about-ov-r5k':'Core Technology','about-ov-r5v':'Next-generation beauty fintech platform combining K-Beauty, healthcare, e-commerce, and reward systems',
    'about-ov-r6k':'Phone','about-ov-r7k':'Email',
    'about-svc-label':'Core Services','about-svc-title':'Core <em>Services</em>',
    'about-svc1-t':'COSBACK','about-svc1-d':'An e-commerce platform for K-Beauty, healthcare, fashion, travel, and lifestyle products. Earn various rewards based on purchases and partner benefits.',
    'about-svc2-t':'Dr. Reward','about-svc2-d':'A mobile platform combining wellness information from clinics, hair, nail, Pilates, and more with reward accumulation. Expanding touchpoints between customers and brands.',
    'about-svc3-t':'Hybrid Ecosystem','about-svc3-d':'A hybrid platform structure connecting K-Beauty, clinic & wellness info, customer rewards, and financial & insurance services through COSBACK and Doctor Reward.',
    'about-str-label':'Core Strengths','about-str-title':'Core <em>Strengths</em>',
    'about-str-sub':'BIGWAVE3 creates sustainable growth through differentiated competitiveness connecting beauty, healthcare, and fintech.',
    'about-str1-h':'Dual-Platform Structure: E-Commerce + Clinic Info','about-str1-p':'COSBACK is the central platform for product purchases and reward accumulation, while Doctor Reward serves as the touchpoint for clinic information and wellness benefits. Each platform operates independently while functioning as one connected beauty fintech ecosystem within the customer experience.',
    'about-str2-h':'K-Beauty Brand Distribution Foundation','about-str2-p':'We are strengthening our product-based customer acquisition structure through distribution and platform integration with premium domestic K-Beauty brands. Rather than focusing purely on advertising, we aim for a model where customers become platform members through actual product purchases and usage experiences.',
    'about-str3-h':'Intellectual Property in Reward Systems','about-str3-p':'Our business model is being advanced based on patent decisions related to reward accumulation and redemption systems for cosmetics purchases. This expands into platform technology assets that systematize purchase behavior and reward usage structures.',
    'about-ach-label':'Key Achievement','about-ach-title':'Key <em>Achievements</em>',
    'about-ach-sub':'BIGWAVE3 creates differentiated value<br>through proprietary technology and intellectual property.',
    'about-pat-h':'Patent-Based Technology Assets',
    'about-pat-p':'Patent decisions have been confirmed for the <strong>reward accumulation and redemption system for cosmetics purchases</strong> connected to our core business model, as well as the methods for reward accumulation and redemption performed within that system.',
    'about-pat-note':'This serves as a technical basis for differentiating the reward structures of COSBACK and Doctor Reward going forward.',
    'about-tag1-t':'IP Foundation','about-tag1-s':'Proprietary technology assets secured',
    'about-tag2-t':'Business Synergy','about-tag2-s':'Direct link to core business model',
    'about-tag3-t':'Future Value Creation','about-tag3-s':'Sustainable competitive advantage',
    'about-vis-label':'Vision','about-vis-title':'BIGWAVE3\'s <em>Vision</em>',
    'about-vis-quote':'<span class="vq-mark">"</span>Expanding K-Beauty purchase experiences into <em>reward financial experiences</em>,<br>connecting clinic information and wellness benefits ??br>a global beauty fintech platform<span class="vq-mark">"</span>',
    'about-vis-desc':'BIGWAVE3 aims to go beyond simple product purchases, creating a new consumption structure where benefits are accumulated during the purchase process and those benefits are reconnected to wellness and clinic experiences.',
    'about-vis-divider':'BIGWAVE3 is <strong>redesigning the purchase experience in the beauty industry around data and rewards</strong>.',
    'about-closing-p1':'<strong>COSBACK</strong> handles the scalability of K-Beauty e-commerce,<br>while <strong>Doctor Reward</strong> connects clinic information and wellness reward experiences.',
    'about-closing-p2':'We will continue to grow as an innovative platform company connecting K-Beauty, healthcare, fintech, and global distribution.',
  },

  ja: {
    'nav-overview':'礖귟쫨','nav-ir':'IR蘊뉑뼑若?,
    'nav-cosback':'?녈궧?먦긿??,'nav-dreward':'Dr.?ゃ꺈?쇈깋','nav-member':'?쀣꺃?잆궋??,
    'nav-compare':'?밧끂驪붻펱','nav-media':'?▲깈?ｃ궋','nav-cta':'IR蘊뉑뼑獄뗦콆',
    'nav-sub-cos1':'COSBACK?ャ겇?꾠겍','nav-sub-cos2':'獰롥?蘊뉒뵣?ャ꺖??,'nav-sub-cos3':'?듐깲?밤꺍?ャ꺖??iD VITA',
    'nav-sub-dr1':'Dr.?ゃ꺈?쇈깋?ャ겇?꾠겍','nav-sub-dr2':'?듐깲?밤꺍?ョ겱岳앶쇇',
    'nav-sub-mem1':'Great Beauty?▲꺍?먦꺖?룔긿??,'nav-sub-media2':'?▲깈?ｃ궋?깁걪',
    'hero-badge':'訝뽫븣??CosTechMed 獰롥??뺛궍?녈깇?껁궚?ⓦ궠?룔궧?녴깲',
    'hero-h1':'易덅꼇?뚩퀒?ｃ겓?ゃ굥<br><em>K-?볝깷?쇈깇?ｃ꺖??쑋??/em>',
    'hero-sub':'?뽫꺌?곥겗易덅꼇??strong>??깵?껁궥?γ깘?껁궚</strong>?ャ겒?듽?br>?썼죹?ゃ꺈?쇈깋?ャ겒?듽?strong>若됧퓘岳앶쇇</strong>?ャ겒?듽겲?쇻?br>BIGWAVE3??궠?밤깘?껁궚?쭰r.?ゃ꺈?쇈깋?믥퉳?롢?br>易덅꼇?뚩퀒?ｃ겓?ゃ굥K-?볝깷?쇈깇?ｃ꺖?ⓦ궠?룔궧?녴깲?믢퐳?듽겲?쇻?,
    'hero-btn1':'?쀣꺃?잆궋?좂돶?멥굮誤뗣굥 ??,'hero-btn2':'?녈궧?먦긿??굮誤뗣굥','hero-btn3':'Dr.?ゃ꺈?쇈깋?믥윥??,
    'hero-plbl':'?묆꺖?덀깏?쇈궥?껁깤',
    'marquee':'COSBACK <span class="mstar">??/span> ?鸚?0%??깵?껁궥?γ깘?껁궚 <span class="mstar">??/span> Dr.?ゃ꺈?쇈깋 <span class="mstar">??/span> ?먩맳??꺁?뗣긿??,000?? <span class="mstar">??/span> Samsung Card iD VITA <span class="mstar">??/span> Samsung Fire 獰롥??긱궋岳앶쇇 <span class="mstar">??/span> 103?ュ쎖?겹꺆?쇈깘??<span class="mstar">??/span> 2032亮답폏??00訝뉏볶??쮽 <span class="mstar">??/span> CosTechMed Platform <span class="mstar">??/span>',
    'sec-metrics-h':'BIGWAVE3 <em>訝삭쫨?뉑쮽</em>訝誤?,
    'mc1-lbl':'?т볶蘊쇔뀯??깵?껁궥?γ깘?껁궚','mc1-desc':'?녈궧?먦긿??뀯佯쀣깣?⒲꺍?됭낵?ζ셽?ユ?鸚㎫찉塋?,
    'mc2-lbl':'?뗩걫榮밥퍔?↓솏??깵?껁궥?γ깘?껁궚','mc2-desc':'?먩맳?듐깲?밤꺍?ャ꺖?됪군歷덃셽?ュ룍?붻낵?ι죲?뷸틬',
    'mc3-lbl':'亮닻뼋?겹꺃?쇈깉?볝깷?쇈깇?ｃ꺖??긿??,'mc3-desc':'?쀣꺃?잆궋?졽폏?▼뒥?ζ셽??뭅?볡돶?며쎑壤볣죲',
    'mc4-lbl':'5亮당눕鼇덀깤?с깱?㏂깲堊▼?,'mc4-desc':'?쀣꺃?잆궋?졽폏?←땟?곫셽??눕鼇덄돶?멩렓嶸?,
    'mc5-lbl':'?묆꺖?덀깏?쇈궚?ゃ깑?껁궚?띲긿?덀꺈?쇈궚','mc5-desc':'??넎燁묆꺕壤€닇鸚뽫쭛500??+ 閭?쭛?삣ĳ雅븀쭛500??,
    'mc6-lbl':'?겹꺆?쇈깘?ヨ?沃욁궢?앫꺖??,'mc6-desc':'2032亮답폏?←쎅與?00訝뉏볶',
    'sec-ctm-h':'CosTechMed <em>?㏂꺖??깇??긽??/em>',
    'sec-ctm-lead':'Cosmetics 횞 Technology 횞 Medical ??易덅꼇?믦퀒?ｃ겓鸚됪룢?쇻굥訝뽫븣?앫겗?ⓦ궠?룔궧?녴깲',
    'ctm-cos-h':'?ε만易덅꼇?쀣꺀?껁깉?뺛궔?쇈깲','ctm-cos-p':'?뽫꺌?곥꺕?ε볜繇잌뱚?삠깢?▲긿?룔깾?녈꺕?낁죱?ゃ겑?ε만??꺀?ㅳ깢?밤궭?ㅳ꺂易덅꼇?믡궠?밤깘?껁궚?㏛??껆??녴?,
    'ctm-cos-t1':'?뽫꺌??,'ctm-cos-t2':'?ε볜繇잌뱚','ctm-cos-t3':'?뺛궊?껁궥?㎯꺍?삥뾽烏?,
    'ctm-tech-h':'?뉎궦?욍꺂?η텥?с궎?ㅳ꺖','ctm-tech-p':'QR沃띹㉫?삠궋?쀣꺁?ｆ맳?삠궘?ｃ긿?룔깷?먦긿??꺕?ゃ꺈?쇈깋?삡퓷?뷩꺕黎뷸툑?ㅳ꺍?뺛꺀?㎪텋縕삠겏?밧끂?믡꺁?㏂꺂?욍궎?졿렏泳싥?,
    'ctm-tech-t1':'QR?삠궋?쀣꺁','ctm-tech-t2':'??깵?껁궥?γ깘?껁궚?삠꺁??꺖??,'ctm-tech-t3':'黎뷸툑?ｆ맳',
    'ctm-med-h':'獰롥?蘊뉒뵣??,'ctm-med-p':'??꺁?뗣긿??깄?긱꺕?썼죹?ゃ꺈?쇈깋??꺃?멥긿?덀꺕Samsung Fire若됧퓘岳앶쇇?ｆ맳?㎪텋縕삠걣獰롥?蘊뉒뵣?ャ?,
    'ctm-med-t1':'??꺁?뗣긿??깄??,'ctm-med-t2':'?썼죹?ゃ꺈?쇈깋','ctm-med-t3':'若됧퓘岳앶쇇',
    'sec-cos-h':'?녈궧?먦긿??br><em>EC?쀣꺀?껁깉?뺛궔?쇈깲</em>',
    'sec-cos-lead':'縕룔걝?잆겞?ョ뤎?묆걣?꾠겂?╉걦?뗦닇?쒎엹EC ????깵?껁궥?γ깘?껁궚?쭰r.?ゃ꺈?쇈깋?뚨퉳?뚣굤?얇걲??,
    'cof1-lbl':'?т볶蘊쇔뀯??깵?껁궥?γ깘?껁궚','cof1-desc':'?녈궧?먦긿??뀯佯쀣깣?⒲꺍?됥겎蘊쇔뀯?귝?鸚?0%?얗뇫令띸쳦',
    'cof2-lbl':'?뗩걫榮밥퍔?↓솏??깵?껁궥?γ깘?껁궚','cof2-desc':'榮밥퍔?ゃ꺍??걢?됧뒥?γ걮?잌룍?붵걣蘊쇔뀯?쇻굥?잆겞?ョ찉塋?,
    'cof3-lbl':'Dr.?ゃ꺈?쇈깋?ｆ맳','cof3-desc':'?녶뱚QR?밤궘?ｃ꺍?㎫풆若방뼺烏볝꺁??꺖?됥걣?ゅ땿?ｆ맳',
    'cof4-lbl':'?ャ깇?담꺁??,'cof4-desc':'Beauty 쨌 Health 쨌 Fashion 쨌 Travel ?ⓦ궖?녴궡?ゃ꺖',
    'cos-brands-lbl':'?ε틭?뽧꺀?녈깋堊?,
    'cos-float1':'餓딀쐢??궘?ｃ긿?룔깷?먦긿??찉塋?,'cos-float2':'Dr.?ゃ꺈?쇈깋?ｆ맳歷덀겳',
    'sec-loop-h':'獰롥? <em>蘊뉒뵣?ャ꺖??/em> ?ャ궧?욍깯?쇈궦?ｃ꺖?뗣꺖',
    'sec-loop-lead':'From First Purchase to Infinite Cashback ??br>10-Step Beauty Asset Journey',
    'ls1':'???녈궧?먦긿??br>?졾뀯','ls2':'???쀣꺃?잆궋??br>?밧끂?됧듅??,'ls3':'???뽧꺀?녈깋<br>?녶뱚蘊쇔뀯','ls4':'????깵?껁궥??br>?먦긿??찉塋?,'ls5':'??QR<br>?밤궘?ｃ꺍',
    'ls6':'??Dr.?ゃ꺈?쇈깋<br>令띸쳦','ls7':'????꺁?뗣긿??br>?끻젿?®뇨','ls8':'???썼죹孃?br>?ゃ꺈?쇈깋域사뵪','ls9':'??Samsung Fire<br>岳앶쇇?ｆ맳','ls10':'???뗩걫榮밥퍔<br>?↓솏??깵?껁궥?γ깘?껁궚',
    'loop-b1':'?녈궧?먦긿????깵?껁궥?γ깘?껁궚','loop-b2':'Dr.?ゃ꺈?쇈깋 ??꺃?멥긿??,'loop-b3':'Samsung Fire 若됧퓘岳앶쇇','loop-b4':'?↓솏??깵?껁궥?γ깘?껁궚?ャ꺖?녴궍??,
    'sec-sc-h':'Samsung Card <em>iD VITA</em><br>?먩맳?묋엻?ャ꺖?녴궍??,
    'sec-sc-lead':'COSBACK 횞 Samsung Card iD VITA ???듿?礪섅걣?ゃ굢?멥겤?밤깯?쇈깉?ゃ깤?с깱?㏂깲邕€룢?ⓦ꺍?멥꺍',
    'scf1-t':'??꺁?뗣긿??꺕?у??밧끂','scf1-d':'?묆꺖?덀깏?쇈궚?ゃ깑?껁궚?삭뼩掠?㎯겗?밧닪?밧끂',
    'scf2-t':'?잍뉵?섇윜?밧끂','scf2-d':'?ε만?잍뉵?②닾??궖?쇈깋?밧끂',
    'scf3-t':'?鸚?5%?↓솏??깵?껁궥?γ깘?껁궚','scf3-d':'?먩맳?듐깲?밤꺍?ャ꺖?됪군歷덃셽?ュ룍?붻낵?ι죲??5%',
    'scf4-t':'Samsung Fire 岳앶쇇?ｆ맳','scf4-d':'獰롥??긱궋若됧퓘岳앶쇇?믡궋?쀣꺁?㎯꺁?㏂꺂?욍궎?좂▶沃?,
    'paths-lbl':'?쀣꺃?잆궋?졽폏?▼뒥?η탪瓮?,
    'piA-tag':'Path A','piA-t':'?얗뇫??돂??,'piA-d':'亮답폏縕???50,000 ?닸렏??돂',
    'piB-tag':'Path B 狩??듽걲?쇻굙','piB-t':'iD VITA ?ょ쇇?꾢뒥?ε엹','piB-d':'?듿?礪섅겗?ょ뵳?ら겦????凉룟댍?ゃ걮',
    'sc-float1-t':'?뗩걫榮밥퍔??깵?껁궥?γ깘?껁궚','sc-float1-s':'?먩맳?듐깲?밤꺍?ャ꺖?됪군歷덃셽',
    'sc-float2-t':'獰롥??긱궋岳앶쇇','sc-float2-s':'Samsung Fire ?ｆ맳若뚥틙',
    'sec-dr-h':'Dr. Reward<br><em>?㏂깘?ㅳ꺂?쀣꺀?껁깉?뺛궔?쇈깲</em>',
    'drf1-t':'?ゃ꺈?쇈깋閻븃첀','drf1-d':'蘊쇔뀯?팓R?밤궘?ｃ꺍?삠깤?с깱?㏂깲?밧끂?삣룍?붺뉩餓뗣겎縕?겲?ｃ걼?ゃ꺈?쇈깋?믡궋?쀣꺁?㏛?誤㎫▶沃?,
    'drf2-t':'??꺁?뗣긿??깄?길렋榮?,'drf2-d':'??넎燁묆꺕壤€닇鸚뽫쭛?삥뼺烏볝궖?녴궡?ゃ꺖?삣쑑?잌닪??꺁?뗣긿??깄?긱굮?ょ뵳?ユ렋榮㏂귛섭?뜻렓?╉겒??,
    'drf3-t':'?썼죹孃뚣궚?с궦?껁깉域사뵪','drf3-d':'岳앮쐣?ゃ꺈?쇈깋?믤뼺烏볟풄??군歷덃??롢겎??꺃?멥긿?덀겏?쀣겍域사뵪',
    'drf4-t':'岳앶쇇?뜻뀑閻븃첀','drf4-d':'Samsung Fire 獰롥??긱궋若됧퓘岳앶쇇??ｆ맳?뜻뀑?믡궋?쀣꺁?㎯꺁?㏂꺂?욍궎?좂▶沃?,
    'dr-float1-s':'?ゃ꺈?쇈깋令띸쳦若뚥틙','dr-float2-s':'?묆꺖?덀깏?쇈궚?ゃ깑?껁궚?띲긿?덀꺈?쇈궚',
    'sec-gb-h':'?겹꺃?쇈깉?볝깷?쇈깇?ｃ꺖 <em>?쀣꺃?잆궋??/em> 鴉싧뱻?밧끂',
    'sec-gb-lead':'亮닻뼋堊▼???00,000 ???쀣꺃?잆궋?좂풆若밤깢?ｃ꺍?녴긿??폏??,
    'gb-badge':'亮?0訝뉎궑?⒲꺍?멨퐪',
    'gbc1-t':'Dr.?ゃ꺈?쇈깋 ?썼죹?ゃ꺈?쇈깋','gbc1-v':'??00,000?멨퐪','gbc1-d':'?묆꺖?덀깏?쇘슢?싩쭛?삣숱?먨쨼燁묆겎鵝욍걟?뗧풆若밤꺁??꺖?됥궚?с궦?껁깉',
    'gbc2-t':'Samsung Fire 獰롥??긱궋若됧퓘岳앶쇇','gbc2-v':'1亮당꽒?잋퓷??,'gbc2-d':'?썼죹孃뚣겗??퐳?ⓦ꺕孃뚪겫?뉎꺁?밤궚??궩?쇈깢?녴궍?띲긿?덀괕IGWAVE3?뚥퓷?뷸뼑?믤뵱??,
    'gbc3-t':'?쀣꺃?잆궋?졼??쇈깯?녈궧?▲궩?껁깉','gbc3-v':'??50,000?멨퐪','gbc3-d':'?썼죹?띶풄??굦?녈꺍?뉎궍?룔깾?녕??녴겗?잆굙??깫?쇈깲?긱궋獒썲뱚',
    'gbc4-t':'?↓솏??깵?껁궥?γ깘?껁궚?ャ꺖?녴궍??,'gbc4-v':'?▼댍?먪찉塋?,'gbc4-d':'?뗩걫榮밥퍔?ⓦ궠?밤깘?껁궚蘊쇔뀯?ャ굠?뗧텤泳싩쉪?ょ뤎?묆궘?ｃ긿?룔깷?먦긿??,
    'gj-t':'?얇걳?→뼑?㎩쭓?곥겲?쀣굟??,'gj-s':'?겹꺃?쇈깉?볝깷?쇈깇?ｃ꺖?밧끂??깤?с깱?㏂깲鴉싧뱻?먨츣?㎯걲',
    'gjpA':'A????亮답폏縕???50,000 ??돂??,'gjpB':'B????iD VITA ?ょ쇇?꾢뒥?ε엹 狩?,
    'sec-cmp-h':'訝?т폏??vs <em>?쀣꺃?잆궋?졽폏??/em> ?밧끂驪붻펱',
    'ch-gen-lbl':'General Member','ch-gen-t':'訝?т폏??,'ch-gen-sub':'?→뼑?졾뀯',
    'ch-prem-lbl':'Premium Member','ch-prem-t':'?쀣꺃?잆궋?졽폏??,'ch-prem-sub':'亮답폏縕삠겲?잆겘?먩맳?ャ꺖?됬쇉??,
    'cr1':'?썚 ?녈궧?먦긿??낵??,'cr2':'?뮥 ?т볶??깵?껁궥?γ깘?껁궚','cr3':'?뫁 ?뗩걫榮밥퍔??깵?껁궥?γ깘?껁궚',
    'cr4':'?룯 Dr.?ゃ꺈?쇈깋','cr5':'?럞 ?겹꺃?쇈깉?볝깷?쇈깇?ｃ꺖??긿??,'cr6':'?썳 Samsung Fire 岳앶쇇','cr7':'?뵕 榮밥퍔?녈꺖??,
    'gen-v1':'??꺗','gen-v2':'?뷸쑍?밧끂','gen-v3':'?띌솏?귙굤','gen-v4':'訝?ⓩ깄?긱겗??,'gen-v5':'?욄룓堊?,'gen-v6':'?욄룓堊?,'gen-v7':'?싧만榮밥퍔',
    'gen-foot':'鵝볣쮶窈㎩? 쨌 ?덀꺀?뺛궍?껁궚?ⓦ꺍?멥꺍',
    'prem-v1':'?鸚㎫돶????,'prem-v2':'?鸚?0% ??,'prem-v3':'?듐깲?밤꺍?ャ꺖?됪?鸚?5%?↓솏 ??,
    'prem-v4':'?썼죹?ゃ꺈?쇈깋令띸쳦?삥뉵????,'prem-v5':'亮?0訝뉎궑?⒲꺍?멨퐪 ??,'prem-v6':'?ｆ맳??꺗 ??,'prem-v7':'?ゃ꺖?듽꺖?룔긿?쀧뉩餓뗣궠?쇈깋 ??,
    'prem-foot':'?녈궋?밧끂窈㎩? 쨌 ?롧썗?ⓦ꺍?멥꺍','prem-cta':'?쀣꺃?잆궋?좂돶?멥굮?됧듅?뽧걲????,
    'sec-tv-h':'Dr. Reward TV <em>?▲깈?ｃ궋?삠꺍?욍꺖</em>',
    'sec-tv-lead':'3?녴겎?뤵걢?뗧풆若밤깢?ｃ꺍?녴긿?????녈궧?먦긿??꺕Dr.?ゃ꺈?쇈깋?삡퓷?뷩꺕?뺠퀒?얇겎',
    'tv-main-title':'易덅꼇?뚩퀒?ｃ겓?ゃ굥也뉓래??br>CosTechMed??쭓?얇굤',
    'tv-it1':'Samsung Fire 岳앶쇇旅덂냵','tv-it2':'Samsung Card iD VITA 旅덂냵',
    'tv-it3':'窈㎩??ㅳ꺍?욍깛?γ꺖 ??易덅꼇?뚩퀒?ｃ겓?ゃ겂?잋퐪蟯?,'tv-it4':'??넎燁묌솫?룔궎?녈궭?볝깷?????삣릊?뚩쫳?뗧풆若밤꺁??꺖??,
    'tv-it5':'?뺠퀒若뜰궎?녈궭?볝깷????獰롥??뺛궍?녈깇?껁궚?겼툊??,
    'tv-more':'?ⓨ땿?삠굮誤뗣굥 ??,
    'cta-h2':'BIGWAVE3 ?ⓦ궠?룔궧?녴깲??br><em>餓듽걲?먨뢿??/em>',
    'cta-p':'窈㎩??삠깣?⒲꺍?됥꺕??꺁?뗣긿??꺕?뺠퀒若뜰걲?밤겍??걼?곥겗濚뗣걣?듽걣?볝걪?뗣굢冶뗣겲?듽겲??,
    'ctac1-t':'窈㎩?','ctac1-d':'?겹꺃?쇈깉?볝깷?쇈깇?ｃ꺖?쀣꺃?잆궋?졽폏?▲겓?ゃ겂?╉궘?ｃ긿?룔깷?먦긿??꺕?썼죹?ゃ꺈?쇈깋?삣츎恙껂퓷?뷩굮冶뗣굙?덀걝','ctac1-btn':'?쀣꺃?잆궋?졾뒥????,
    'ctac2-t':'?뽧꺀?녈깋','ctac2-d':'佯껃몜縕삠겒?쀣겎?먩옖?쇻꺖?밤겎窈㎩??ョ돶?멥걣?꾠굥?녈궧?먦긿??겦??뀯佯쀣굮冶뗣굙?덀걝','ctac2-btn':'?뽧꺀?녈깋?ε틭?녘쳦 ??,
    'ctac3-t':'?묆꺖?덀깏?쇈궚?ゃ깑?껁궚','ctac3-d':'遙섌뼟訝롢겗獰롥?窈㎩??①퉳?뚣굥Dr.?ゃ꺈?쇈깋?묆꺖?덀깏?쇈궚?ゃ깑?껁궚?ャ겒?띲걝','ctac3-btn':'??꺁?뗣긿??뵵獄???,
    'ctac4-t':'?뺠퀒若?,'ctac4-d':'CosTechMed?ⓦ궠?룔궧?녴깲??닇?룡㎯겏?뺠퀒艅잋폏?믡걫閻븃첀?뤵걽?뺛걚','ctac4-btn':'IR蘊뉑뼑獄뗦콆 ??,
    'cta-bottom-p':'易덅꼇??굚??굜易덀걟?╉걚?뤵궠?밤깉?㎯겘?귙굤?얇걵??,
    'ft-brand-p':'易덅꼇?뚩퀒?ｃ겓?ゃ굥訝뽫븣?앫겗CosTechMed獰롥??뺛궍?녈깇?껁궚?ⓦ궠?룔궧?녴깲?괖OSBACK?쭰r.?ゃ꺈?쇈깋?갨amsung Card?팗amsung Fire?뚦뀻?ャ걗?듽겲?쇻?,
    'ft-l1':'?녈궧?먦긿??(COSBACK)','ft-l2':'Dr.?ゃ꺈?쇈깋','ft-l3':'?겹꺃?쇈깉?볝깷?쇈깇?ｃ꺖?쀣꺃?잆궋??,'ft-l4':'Dr. Reward TV',
    'ft-l5':'?뽧꺀?녈깋?ε틭?녘쳦','ft-l6':'??꺁?뗣긿??뀯佯쀧뵵獄?,'ft-l7':'Samsung Card ?먩맳','ft-l8':'Samsung Fire ?ｆ맳',
    'ft-l9':'鴉싩ㅎ榮밥퍔','ft-l10':'IR蘊뉑뼑獄뗦콆','ft-l11':'?뗣깷?쇈궧?ャ꺖??,'ft-l12':'?⑴뵪誤뤹큵 쨌 ?쀣꺀?ㅳ깘?룔꺖?앫꺁?룔꺖',
    /* ABOUT PAGE */
    'about-nav-ir':'IR?ャ꺖??,
    'about-nav-back':'?쎼꺖?졼겦?삠굥',
    'about-hero-label':'鴉싩ㅎ榮밥퍔',
    'about-hero-h1':'?볝깷?쇈깇?ｃ꺖易덅꼇??em>蘊뉒뵣??/em><br>?ㅳ겒?먦깤?⒲긿?덀깢?⒲꺖??,
    'about-hero-sub':'K-?볝깷?쇈깇?ｃ꺖?곥깦?ャ궧?긱궋?갋C?곥꺁??꺖?됥궥?밤깇?졼굮永꾠겳?덀굩?쎼걼<br>轝▽툟餓ｃ깛?γ꺖?녴궍?쇈깢?ｃ꺍?녴긿??펯璵?,
    'about-ov-label':'鴉싩ㅎ礖귟쫨','about-ov-title':'鴉싩ㅎ <em>礖귟쫨</em>',
    'about-ov-r1k':'鴉싩ㅎ??,'about-ov-r2k':'餓ｈ〃??,'about-ov-r2v':'?썬꺕?잆꺍??,
    'about-ov-r3k':'鼇?쳦??,'about-ov-r3v':'2024亮?1??4??,
    'about-ov-r4k':'訝삭쫨雅뗦??녽뇦','about-ov-r4v':'?뽫꺌?곩뜽鶯꿩??곥궫?뺛깉?╉궒?㏂꺕?룔궧?녴깲?뗧쇇?곫깄?깁싦에璵?곩뙸?у뱚??ｇ탪?뜰궠?녈궢?ャ깇?ｃ꺍??,
    'about-ov-r5k':'訝삭쫨?烏?,'about-ov-r5v':'K-?볝깷?쇈깇?ｃ꺖?곥깦?ャ궧?긱궋?갋C?곥꺁??꺖?됥궥?밤깇?졼굮永꾠겳?덀굩?쎼걼轝▽툟餓ｃ깛?γ꺖?녴궍?쇈깢?ｃ꺍?녴긿??깤?⒲긿?덀깢?⒲꺖??,
    'about-ov-r6k':'?삭㈀?ゅ뤇','about-ov-r7k':'?▲꺖??,
    'about-svc-label':'?녈궋?듐꺖?볝궧','about-svc-title':'訝삭쫨 <em>?듐꺖?볝궧</em>',
    'about-svc1-t':'?녈궧?먦긿??,'about-svc1-d':'K-?볝깷?쇈깇?ｃ꺖?곥깦?ャ궧?긱궋?곥깢?▲긿?룔깾?녈곫뾽烏뚣곥꺀?ㅳ깢?밤궭?ㅳ꺂?녶뱚?믣읃?ㅳ겏?쀣걼EC?쀣꺀?껁깉?뺛궔?쇈깲?귟낵縕룡뉵?뺛겏?먩맳?밧끂?ュ읃?γ걤?뺛겲?뽧겲?ゃ꺁??꺖?됥굮令띲겳塋뗣겍?됥굦?얇걲??,
    'about-svc2-t':'Dr.?ゃ꺈?쇈깋','about-svc2-d':'?낂솫?꾠깦?㏂곥깓?ㅳ꺂?곥깞?⒲깇?ｃ궧?ゃ겑?╉궒?ャ깓?방깄?긱굮?먧풘?쀣곥꺁??꺖?됬찉塋뗣굮永꾠겳?덀굩?쎼걼?㏂깘?ㅳ꺂?쀣꺀?껁깉?뺛궔?쇈깲?귡¨若㏂겏?뽧꺀?녈깋??렏?밤굮?▼ㄷ?쀣겲?쇻?,
    'about-svc3-t':'?뤵궎?뽧꺁?껁깋?ⓦ궠?룔궧?녴깲','about-svc3-d':'COSBACK?쭰octor Reward?믢릎恙껁겓?갞-?볝깷?쇈깇?ｃ꺖?사뾽?㏂궑?㎯꺂?띲궧?끻젿?삯¨若㏂꺁??꺖?됥꺕?먩맳?묋엻岳앶쇇?듐꺖?볝궧?믡겇?ゃ걧?뤵궎?뽧꺁?껁깋?쀣꺀?껁깉?뺛궔?쇈깲礪뗩졼?,
    'about-str-label':'?녈궋凉룔겳','about-str-title':'訝삭쫨 <em>凉룔겳</em>',
    'about-str-sub':'?볝깷?쇈깇?ｃ꺖?삠깦?ャ궧?긱궋?삠깢?ｃ꺍?녴긿??굮?ㅳ겒?륛IGWAVE3??량?ε뙑?뺛굦?잏ザ雅됧뒟?㎪똻泳싧룾?썬겒?먬빓?믣츪?얇걮?얇걲??,
    'about-str1-h':'EC?①뾽?€깄?긱깤?⒲긿?덀깢?⒲꺖?졼겗?뉎깷?㏂꺂礪뗩?,'about-str1-p':'COSBACK??＝?곮낵縕룔겏?ゃ꺈?쇈깋令띸쳦??릎?멥깤?⒲긿?덀깢?⒲꺖?졼겎?귙굤?갆octor Reward??뾽?€깄?길룓堊쎼겏?╉궒?ャ깓?밭돶?멥겗?η궧?쀣꺀?껁깉?뺛궔?쇈깲?㎯걲?귛릢?쀣꺀?껁깉?뺛궔?쇈깲??떖塋뗣걮?ゃ걣?됥굚?곲¨若㏘퐪蟯볝겗訝?겎????ㅳ겗?볝깷?쇈깇?ｃ꺖?뺛궍?녈깇?껁궚?ⓦ궠?룔궧?녴깲?ⓦ걮??찣?썬걮?얇걲??,
    'about-str2-h':'K-?볝깷?쇈깇?ｃ꺖?뽧꺀?녈깋役곲싧읃??,'about-str2-p':'?썲냵?쀣꺃?잆궋?쟇-?볝깷?쇈깇?ｃ꺖?뽧꺀?녈깋?ⓦ겗役곲싥꺕?쀣꺀?껁깉?뺛궔?쇈깲?ｅ땿?믧싥걯??＝?곥깧?쇈궧??¨若€탛?ζ쭓?졼굮凉룟뙑?쀣겍?꾠겲?쇻귛틕?듾릎恙껁겎??겒?뤵곩츪?쎼겗獒썲뱚蘊쇠껭?ⓧ슴?ⓧ퐪蟯볝굮?싥걯?╉깤?⒲긿?덀깢?⒲꺖?졽폏?▲겦邕€룢?쇻굥礪뗩졼굮??뙁?쀣겲?쇻?,
    'about-str3-h':'?ゃ꺈?쇈깋?룔궧?녴깲??ｇ윥?꾥깹?ｅ읃??,'about-str3-p':'?뽫꺌?곮낵縕룔겓鴉담걝?ゃ꺈?쇈깋令띸쳦?삡슴?ⓦ궥?밤깇?졼겓?㏂걲?뗧돶鼇길군若싥굮?뷩겓?볝궦?띲궧?㏂깈?ャ걣遙섇벧?뽧걮?╉걚?얇걲?귟낵縕룩죱?뷩겏?ゃ꺈?쇈깋鵝욜뵪礪뗩졼굮?룔궧?녴깲?뽧걮?잆깤?⒲긿?덀깢?⒲꺖?졿?烏볢퀒?ｃ겏?쀣겍?▼섧?뺛굦?얇걲??,
    'about-ach-label':'訝삭쫨若잏맘','about-ach-title':'訝삭쫨 <em>若잏맘</em>',
    'about-ach-sub':'BIGWAVE3??떖?ゃ겗?烏볟뒟??br>?η쉪縕←뵣?믣읃?ㅳ겓藥?닪?뽧걬?뚣걼堊▼ㅳ굮?드눣?쀣겲?쇻?,
    'about-pat-h':'?배㉠黎뷴츣?ュ읃?γ걦?烏볢퀒??,
    'about-pat-p':'壤볡ㅎ??졇恙껁깛?멥깓?밤깴?뉎꺂?③ｇ탳?쇻굥<strong>?뽫꺌?곮낵縕룔겓鴉담걝?ゃ꺈?쇈깋令띸쳦?삡슴?ⓦ궥?밤깇??/strong>?곥걡?덀겞?앫겗?룔궧?녴깲?㎬죱?뤵굦?뗣꺁??꺖?됬찉塋뗣꺕鵝욜뵪?방퀡?ラ뼟?쇻굥?배㉠黎뷴츣?뚨▶沃띲걬?뚣겲?쀣걼??,
    'about-pat-note':'?볝굦?츮OSBACK?쭰octor Reward??꺁??꺖?됪쭓?졼굮藥?닪?뽧걲?뗦?烏볡쉪?방떊?ⓦ걮??뉵?ⓦ걬?뚣겲?쇻?,
    'about-tag1-t':'?θ깹?븀썶','about-tag1-s':'?ц눎?烏볢퀒?ｃ굮閻뷰퓷',
    'about-tag2-t':'雅뗦??ｆ맳凉룟뙑','about-tag2-s':'?멨퓘?볝궦?띲궧?㏂깈?ャ겏?닸렏?ｇ탳',
    'about-tag3-t':'?ゆ씎堊▼ㅵ돲??,'about-tag3-s':'?곭텥??꺗?ょザ雅됧꽛鵝?,
    'about-vis-label':'?볝궦?㎯꺍','about-vis-title':'BIGWAVE3??<em>?볝궦?㎯꺍</em>',
    'about-vis-quote':'<span class="vq-mark">"</span>K-?볝깷?쇈깇?ｃ꺖蘊쇠껭鵝볣쮶??em>?ゃ꺈?쇈깋?묋엻鵝볣쮶?멩떋凉?/em>?쀣?br>?낂솫?끻젿?ⓦ궑?㎯꺂?띲궧?밧끂?믡겇?ゃ걧<br>?겹꺆?쇈깘?ャ깛?γ꺖?녴궍?쇈깢?ｃ꺍?녴긿??깤?⒲긿?덀깢?⒲꺖??span class="vq-mark">"</span>',
    'about-vis-desc':'BIGWAVE3??뜕?ゃ굥獒썲뱚蘊쇠껭?믦텈?덀곮낵縕룬걥葉뗣겎?밧끂?믥찉?욜쳦?╉곭찉?욜쳦?╉걼?밧끂?믡궑?㎯꺂?띲궧?①뾽?€깄?긴퐪蟯볝겦?띷렏泳싥걲?뗦뼭?쀣걚易덅꼇礪뗩졼굮?듐굤?얇걲??,
    'about-vis-divider':'BIGWAVE3??깛?γ꺖?녴궍?쇘뵣璵?겗蘊쇠껭鵝볣쮶??strong>?뉎꺖?욍겏?ゃ꺈?쇈깋訝?퓘?ュ냽鼇?쮫</strong>?쀣겍?꾠겲?쇻?,
    'about-closing-p1':'<strong>COSBACK</strong>?츺-?볝깷?쇈깇?ｃ꺖EC??떋凉득㎯굮?끹걚??br><strong>Doctor Reward</strong>??뾽?€깄?긱겏?╉궒?ャ깓?밤꺁??꺖?됦퐪蟯볝굮?ㅳ겒?롢겲?쇻?,
    'about-closing-p2':'K-?볝깷?쇈깇?ｃ꺖?삠깦?ャ궧?긱궋?삠깢?ｃ꺍?녴긿??꺕?겹꺆?쇈깘?ユ탛?싥굮?ㅳ겒?먬씓?곁쉪?쀣꺀?껁깉?뺛궔?쇈깲鴉곫??ⓦ걮??닇?룔걮泳싥걨?얇걲??,
  },

  zh: {
    'nav-overview':'礖귟염','nav-ir':'IR壅꾣뼑若?,
    'nav-cosback':'瓦붺렟兀?돥','nav-dreward':'?싧＋也뽩뒻','nav-member':'遙섊벨鴉싧몮',
    'nav-compare':'?껆썗驪붻푵','nav-media':'揶믢퐪','nav-cta':'?녘?IR壅꾣뼑',
    'nav-sub-cos1':'COSBACK餓뗧퍖','nav-sub-cos2':'獰롥쫮壅꾡벨孃ょ렞','nav-sub-cos3':'訝됪삜??iD VITA',
    'nav-sub-dr1':'Dr.也뽩뒻餓뗧퍖','nav-sub-dr2':'訝됪삜?ョ겲岳앶솴',
    'nav-sub-mem1':'Great Beauty鴉싧몮','nav-sub-media2':'揶믢퐪?ι걪',
    'hero-badge':'?①릡腰뽨릉 CosTechMed 獰롥??묋엻燁묉??잍곭내瀯?,
    'hero-h1':'易덅뉩?섋탡雅㎫쉪<br><em>K-獰롥쫮?ゆ씎</em>',
    'hero-sub':'?뽩쫮?곫텋兀밧룜??strong>瓦붺렟</strong>竊?br>?섉닇獰롥?也뽩뒻竊뚦룜??strong>若됧퓘岳앶솴</strong>??br>BIGWAVE3瓦욄렏COSBACK?뚦뜗鶯ュ쪝?깍펽<br>?꾢뻠易덅뉩?섋탡雅㎫쉪K-獰롥쫮?잍곭내瀯잆?,
    'hero-btn1':'?η쐦遙섊벨鴉싧몮?껆썗 ??,'hero-btn2':'?®뇨COSBACK','hero-btn3':'雅녻㎗?싧＋也뽩뒻',
    'hero-plbl':'?덁퐳鴉쇾섦',
    'marquee':'COSBACK <span class="mstar">??/span> ?遙?0%瓦붺렟 <span class="mstar">??/span> ?싧＋也뽩뒻 <span class="mstar">??/span> ?덁퐳?삯솫1,000若? <span class="mstar">??/span> Samsung Card iD VITA <span class="mstar">??/span> Samsung Fire 獰롥?岳앶솴 <span class="mstar">??/span> ?①릡103??<span class="mstar">??/span> 2032亮당쎅??00訝뉏폏??<span class="mstar">??/span> CosTechMed Platform <span class="mstar">??/span>',
    'sec-metrics-h':'BIGWAVE3 <em>?멨퓘?뉑젃</em>訝鰲?,
    'mc1-lbl':'?т볶兀?물瓦붺렟','mc1-desc':'兀?물COSBACK?ι㈊?곭뎹?遙섊㎝榮?,
    'mc2-lbl':'也썲룍?②뜍?좈솏瓦붺렟','mc2-desc':'鵝욜뵪?붷릫訝됪삜?←퍜嶸쀦뿶?됧??뗨눌阿곈뇫窯앲?嶸?,
    'mc3-lbl':'亮닷벧獰롣맒鹽쇔똿','mc3-desc':'遙섊벨鴉싧몮?졾뀯?뜻룓堊쏁쉪亮닷벧?껆썗?멨퐪?묌쥫',
    'mc4-lbl':'5亮당눕溫▽폏?섆뻔??,'mc4-desc':'岳앮똻遙섊벨鴉싧몮?띄쉪榮???껆썗鴉곁츞',
    'mc5-lbl':'?덁퐳?삯솫營묊퍥','mc5-desc':'??궎燁뫢룡빐壤℡쨼燁?00若?+ ?숂쭛쨌倻뉒쭛500若?,
    'mc6-lbl':'?①릡瑥????똻','mc6-desc':'2032亮답폏?섊쎅??00訝뉏볶',
    'sec-ctm-h':'CosTechMed <em>?뜻엫</em>',
    'sec-ctm-lead':'?뽩쫮??횞 ???횞 ?사뼏 ???①릡腰뽨릉弱녷텋兀배쉬?뽨맏壅꾡벨?꾤뵟?곭내瀯?,
    'ctm-cos-h':'?ε만易덅뉩亮녑룿','ctm-cos-p':'?뽩쫮?곥곩겈佯룬짘?곥곫뿶弱싥곫뾽烏뚨춬?ε만?잍뉵易덅뉩?쭯OSBACK亮녑룿瀯잋?嶸←릤??,
    'ctm-cos-t1':'?뽩쫮??,'ctm-cos-t2':'?ε볜繇잌뱚','ctm-cos-t3':'?뜹컶쨌?낁죱',
    'ctm-tech-h':'?겼춻瓦욄렏掠?,'ctm-tech-p':'QR溫ㅸ칮?갂pp?붷뒯?곮퓭?겹곩쪝?긱곦퓷?⒲곫뵱餓섉???읃簾溫얏뼺若욄뿶瓦욄렏易덅뉩訝롦쓢?듽?,
    'ctm-tech-t1':'QR쨌App','ctm-tech-t2':'瓦붺렟쨌也뽩뒻','ctm-tech-t3':'??퍡?붷뒯',
    'ctm-med-h':'獰롥?壅꾡벨??,'ctm-med-p':'?삯솫岳→겘?®뇨?곩뙸獰롥쪝?긺㎝?녴곦툒?잏겓?얍츎恙껂퓷?⑵걫?⑨펽溫⒵텋兀방닇訝븀풆若배탡雅㎯?,
    'ctm-med-t1':'?삯솫岳→겘','ctm-med-t2':'?사풆也뽩뒻','ctm-med-t3':'若됧퓘岳앶솴',
    'sec-cos-h':'COSBACK<br><em>?드븚亮녑룿</em>',
    'sec-cos-lead':'擁딂눌?⑵텏瓦붺렟?꾤빼?덂엹?드븚 ??瓦붺렟訝롥뜗鶯ュ쪝?긷룎?띹퓹?γ?,
    'cof1-lbl':'?т볶兀?물瓦붺렟','cof1-desc':'兀?물COSBACK?ι㈊?곭뎹?遙?0%?곈뇫燁?눕',
    'cof2-lbl':'也썲룍?②뜍?좈솏瓦붺렟','cof2-desc':'?싪퓝?②뜍?얏렏?졾뀯?꾢??뗦캀轝↑눌阿곈꺗?곭뺌燁?눕',
    'cof3-lbl':'?싧＋也뽩뒻?붷뒯','cof3-desc':'?ユ룒?녶뱚QR?ゅ뒯?붷뒯獰롥??사풆也뽩뒻',
    'cof4-lbl':'?곭굳','cof4-desc':'獰롥쫮쨌?ε볜쨌?뜹컶쨌?낁죱 ?ⓨ뱚映?,
    'cos-brands-lbl':'?ι㈊?곭뎹鹽뷰풃',
    'cos-float1':'?ф쐢瓦붺렟燁?눕','cos-float2':'?싧＋也뽩뒻藥꿱퓹??,
    'sec-loop-h':'獰롥? <em>壅꾡벨孃ょ렞</em> 若€댎?끿쮮',
    'sec-loop-lead':'餓롩쫿轝↑눌阿겼댆?좈솏瓦붺렟 ??10閭η풆若배탡雅㎪뾽葉?,
    'ls1':'???졾뀯<br>COSBACK','ls2':'??嚥域?br>遙섊벨鴉싧몮','ls3':'??兀?물<br>?곭뎹?녶뱚','ls4':'??燁?눕<br>瓦붺렟','ls5':'???ユ룒<br>QR',
    'ls6':'??燁?눕<br>?싧＋也뽩뒻','ls7':'???®뇨<br>?삯솫岳→겘','ls8':'???사풆??br>鵝욜뵪也뽩뒻','ls9':'??訝됪삜?ョ겲<br>岳앶솴?붷뒯','ls10':'??也썲룍?②뜍<br>?좈솏瓦붺렟',
    'loop-b1':'COSBACK瓦붺렟','loop-b2':'?싧＋也뽩뒻燁?늽','loop-b3':'訝됪삜?ョ겲若됧퓘岳앶솴','loop-b4':'?좈솏瓦붺렟孃ょ렞',
    'sec-sc-h':'Samsung Card <em>iD VITA</em><br>?붷릫?묋엻?방죭',
    'sec-sc-lead':'COSBACK 횞 Samsung Card iD VITA ??若€댎?や말?됪떓?꾣쇇?썽쳵瀛㏛폏?섋쉬?뽩폊??,
    'scf1-t':'?삯솫쨌??댛?껆썗','scf1-d':'?ⓨ릦鵝쒎뙸?℡룋??댛雅ュ룛?밧닽鴉섉깲',
    'scf2-t':'?잍뉵窯녶윜?껆썗','scf2-d':'?ε만?잍뉵?ⓩ뼶鵝띶댎?→쓢??,
    'scf3-t':'?遙?5%?좈솏瓦붺렟','scf3-d':'鵝욜뵪?붷릫訝됪삜?←퍜嶸쀦뿶?룟풓也썲룍兀?물?묌쥫??5%',
    'scf4-t':'訝됪삜?ョ겲岳앶솴?붷뒯','scf4-d':'?쭭pp訝?츩?뜻윥?뗧풆若방뒪?녶츎恙껂퓷?⑵걫?①듁??,
    'paths-lbl':'遙섊벨鴉싧몮?졾뀯瓮?푶',
    'piA-tag':'瓮?푶A','piA-t':'?곈뇫煐닺뉩??,'piA-d':'?닸렏煐당볐亮닺뉩 ??50,000',
    'piB-tag':'瓮?푶B 狩??②뜍','piB-t':'iD VITA ?ゆ꽴?졾뀯??,'piB-d':'若€댎?や말?됪떓 ???졾성??,
    'sc-float1-t':'也썲룍?②뜍瓦붺렟','sc-float1-s':'鵝욜뵪?붷릫訝됪삜?←퍜嶸쀦뿶',
    'sc-float2-t':'獰롥??ㅷ릤岳앶솴','sc-float2-s':'訝됪삜?ョ겲?붷뒯若뚧닇',
    'sec-dr-h':'Dr. Reward<br><em>燁삣뒯塋?뭄??/em>',
    'drf1-t':'?η쐦也뽩뒻','drf1-d':'?쭭pp訝??鰲덅눌阿겹갦R?ユ룒?곲쳵瀛㏛폏?섉쓢?듽곩??뗦렓?먪㎝榮?쉪??됧쪝??,
    'drf2-t':'?®뇨?삯솫岳→겘','drf2-d':'?됬슢?ㅷ쭛쨌?닷숱鸚뽫쭛쨌?사풆映삣닽쨌?겼뙷?ょ뵳役뤺쭏?삯솫岳→겘?귛??룩눎訝삯됪떓竊뚧뿞凉뷴댍?②뜍',
    'drf3-t':'?사풆?롣슴?①㎝??,'drf3-d':'?ⓨ뙸獰롥릮瀯볡츞?뜻?弱녷똻?됧쪝?긴퐳訝븀㎝?녵슴??,
    'drf4-t':'岳앶솴?뜻곫윥瑥?,'drf4-d':'?쭭pp訝?츩?뜻윥?뗤툒?잏겓?양풆若방뒪?녶츎恙껂퓷?⑵걫?①듁??,
    'dr-float1-s':'也뽩뒻燁?눕若뚧닇','dr-float2-s':'?덁퐳?삯솫營묊퍥',
    'sec-gb-h':'獰롣맒鹽쇤걞 <em>遙섊벨鴉싧몮</em> 訝볟콪?껆썗',
    'sec-gb-lead':'亮닷벧餓룟???00,000 ??遙섊벨獰롥??묋엻燁묉?鴉싧몮',
    'gb-badge':'亮닷벧餓룟?0訝뉔윪??,
    'gbc1-t':'?싧＋也뽩뒻 ?사풆燁?늽','gbc1-v':'餓룟쇄궔300,000','gbc1-d':'??쑉?덁퐳??궎燁뫢룡빐壤℡쨼燁묇슴?①쉪獰롥?也뽩뒻燁?늽',
    'gbc2-t':'訝됪삜?ョ겲 獰롥?若됧퓘岳앶솴','gbc2-v':'1亮닷뀓兀밥퓷??,'gbc2-d':'?사풆?롥돬鵝쒐뵪쨌?롩걮?뉔즼?⒴츎?①퐨?괕IGWAVE3??퍡岳앲뉩',
    'gbc3-t':'遙섊벨?ㅸ궎?곩쪞獒?,'gbc3-v':'餓룟쇄궔150,000','gbc3-d':'?사풆?띶릮?뚩궎?뜻곭??녺쉪若띄뵪?ㅸ궎雅㎩뱚',
    'gbc4-t':'?좈솏瓦붺렟孃ょ렞','gbc4-v':'?좈솏燁?눕','gbc4-d':'?싪퓝也썲룍?②뜍?똂OSBACK兀?돥?곭뺌?룟풓?곈뇫瓦붺렟',
    'gj-t':'?덁퍗?띹뉩凉冶?,'gj-s':'鵝녺풆訝썹ㅌ?뉒돶?껂퍎野백쳵瀛㏛폏?섇???,
    'gjpA':'A????亮닺뉩??50,000 煐닺뉩??,'gjpB':'B????iD VITA ?ゆ꽴?졾뀯??狩?,
    'sec-cmp-h':'??싦폏??vs <em>遙섊벨鴉싧몮</em> ?껆썗野방캈',
    'ch-gen-lbl':'??싦폏??,'ch-gen-t':'??싦폏??,'ch-gen-sub':'?띹뉩?졾뀯',
    'ch-prem-lbl':'遙섊벨鴉싧몮','ch-prem-t':'遙섊벨鴉싧몮','ch-prem-sub':'亮닺뉩?뽬걫?띶뜞力ⓨ냼',
    'cr1':'?썚 COSBACK兀?돥','cr2':'?뮥 ?т볶瓦붺렟','cr3':'?뫁 也썲룍?②뜍瓦붺렟',
    'cr4':'?룯 ?싧＋也뽩뒻','cr5':'?럞 獰롣맒鹽쇔똿','cr6':'?썳 訝됪삜?ョ겲岳앶솴','cr7':'?뵕 ?②뜍??,
    'gen-v1':'??뵪','gen-v2':'?븀??껆썗','gen-v3':'?쀩솏','gen-v4':'?ⓨ늽岳→겘','gen-v5':'訝띷룓堊?,'gen-v6':'訝띷룓堊?,'gen-v7':'??싨렓??,
    'gen-foot':'鵝볣챿?ⓩ댎 쨌 役곲뇧凉뺞뱨',
    'prem-v1':'?鸚㎪쓢????,'prem-v2':'?遙?0% ??,'prem-v3':'訝됪삜?→?遙?5%?좈솏 ??,
    'prem-v4':'?사풆也뽩뒻燁?눕쨌鵝욜뵪 ??,'prem-v5':'亮닷벧餓룟?0訝뉔윪????,'prem-v6':'??걫????,'prem-v7':'訝볟콪?②뜍????,
    'prem-foot':'?멨퓘?껆썗?ⓩ댎 쨌 ?띄썗凉뺞뱨','prem-cta':'嚥域삯쳵瀛㏛폏?섉쓢????,
    'sec-tv-h':'Dr. Reward TV <em>揶믢퐪訝?퓘</em>',
    'sec-tv-lead':'3?녽뮓瑥삥뇗獰롥??묋엻燁묉? ??COSBACK?곩뜗鶯ュ쪝?긱곦퓷?⒲곫뒘壅꾢뀲鰲ｆ옄',
    'tv-main-title':'易덅뉩?섋탡雅㎫쉪也뉓예竊?br>CosTechMed?꾢?冶?,
    'tv-it1':'訝됪삜?ョ겲岳앶솴餓뗧퍖','tv-it2':'Samsung Card iD VITA 餓뗧퍖',
    'tv-it3':'若€댎溫욤컝 ??易덅뉩?섋탡雅㎫쉪雅꿱벴鵝볣챿','tv-it4':'??궎燁묌솫?욤?瘟????사뵟鰲녻쭜訝뗧쉪獰롥?也뽩뒻',
    'tv-it5':'?뺠탡?낁?瘟???獰롥??묋엻燁묉??겼툊??,
    'tv-more':'?η쐦?③깿鰲녽쥜 ??,
    'cta-h2':'?졾뀯BIGWAVE3<br><em>?잍곭내瀯?/em>',
    'cta-p':'訝뷴??룔곩뱚?뚣곩뙸?㏂곫뒘壅꾥끾룓堊쏁쉪瓦욄렏餓롨퓳?뚦?冶?,
    'ctac1-t':'若€댎','ctac1-d':'?먧맏獰롣맒鹽쇤걞遙섊벨鴉싧몮竊뚦?冶뗤벴?쀨퓭?겹곩뙸獰롥쪝?긷뭽若됧퓘岳앶솴','ctac1-btn':'?졾뀯遙섊벨鴉싧몮 ??,
    'ctac2-t':'?곭뎹??,'ctac2-d':'?좈?亮욕몜兀뱄펽餓η빼?덁맏?븀?溫⒴??룩렩孃쀥썮?η쉪COSBACK?ι㈊','ctac2-btn':'?곭뎹?ι㈊?녘? ??,
    'ctac3-t':'?덁퐳?삯솫','ctac3-d':'?먧맏?싧＋也뽩뒻?덁퐳?삯솫竊뚥툗遙섉꼷?묊풆若밧??룟뻠塋뗨퓹??,'ctac3-btn':'?삯솫?ι㈊?녘? ??,
    'ctac4-t':'?뺠탡??,'ctac4-d':'雅녻㎗CosTechMed?잍곭내瀯잏쉪?먬빣逆쒎뒟訝롦뒘壅꾣쑛鴉?,'ctac4-btn':'?녘?IR壅꾣뼑 ??,
    'cta-bottom-p':'易덅뉩訝띶냽??텋鸚긺쉪?먩쑍',
    'ft-brand-p':'?①릡腰뽨릉易덅뉩?섋탡雅㎫쉪CosTechMed獰롥??묋엻燁묉??잍곭내瀯잆괖OSBACK訝롥뜗鶯ュ쪝?깍펽訝됪삜?≤룝툒?잏겓?얍뀻?뚦뢿訝롢?,
    'ft-l1':'COSBACK瓦붺렟','ft-l2':'?싧＋也뽩뒻','ft-l3':'獰롣맒鹽쇤걞遙섊벨鴉싧몮','ft-l4':'Dr. Reward TV',
    'ft-l5':'?곭뎹?ι㈊?녘?','ft-l6':'?삯솫?ι㈊?녘?','ft-l7':'訝됪삜?↑걫??,'ft-l8':'訝됪삜?ョ겲?붷뒯',
    'ft-l9':'?у뤈餓뗧퍖','ft-l10':'IR壅꾣뼑?녘?','ft-l11':'?곈뿻若?,'ft-l12':'鵝욜뵪?→Ь 쨌 ?먪쭅?욜춺',
    /* ABOUT PAGE */
    'about-nav-ir':'IR壅꾣뼑若?,
    'about-nav-back':'瓦붷썮腰뽭〉',
    'about-hero-label':'?у뤈餓뗧퍖',
    'about-hero-h1':'弱녺풆倻녷텋兀?em>饔у뙑訝븃탡雅?/em><br>?꾢뭄??,
    'about-hero-sub':'?띶릦K-獰롥쫮?곩뙸?쀥겈佯룔곭뵷?녴곩쪝?긺내瀯잏쉪<br>訝뗤?餓ｇ풆若백뇫?띸쭛?亮녑룿鴉곦툣',
    'about-ov-label':'?у뤈礖귛넻','about-ov-title':'?у뤈 <em>礖귛넻</em>',
    'about-ov-r1k':'?у뤈?띸㎞','about-ov-r2k':'餓ｈ〃??,'about-ov-r2v':'孃먩븦??,
    'about-ov-r3k':'?먪쳦?ζ쐿','about-ov-r3v':'2024亮?1??4??,
    'about-ov-r4k':'訝삭쫨訝싧뒦窯녶윜','about-ov-r4v':'?뽩쫮?곫돶?묆곮쉴餓뜹룋楹사퍨凉?묆곦에??싦에訝싥곩뙸??쎑?녕퍘?ε뮜瑥?,
    'about-ov-r5k':'?멨퓘???,'about-ov-r5v':'?띶릦K-獰롥쫮?곩뙸?쀥겈佯룔곭뵷?녴곩쪝?긺내瀯잏쉪訝뗤?餓ｇ풆若백뇫?띸쭛?亮녑룿',
    'about-ov-r6k':'?듣캕','about-ov-r7k':'???',
    'about-svc-label':'?멨퓘?띶뒦','about-svc-title':'?멨퓘 <em>?띶뒦</em>',
    'about-svc1-t':'COSBACK','about-svc1-d':'餓쩕-獰롥쫮?곩뙸?쀥겈佯룔곫뿶弱싥곫뾽歷멥곭뵟域삥뼶凉뤶벨?곦맏?븀??꾤뵷?녶뭄?겹귛룾?뷰틢兀?물域삣뒯?뚦릦鵝쒐돶?껆㎝榮?릢燁띶쪝?긱?,
    'about-svc2-t':'?싧＋也뽩뒻','about-svc2-d':'?먧풘?삯솫?딁풆?묆곭풆?꿔곫솹?됪룓嶺됧겈佯룝에??펽亮띄퍜?덂쪝?긺㎝榮?쉪燁삣뒯亮녑룿?귝돥鸚㎩??룝툗?곭뎹?당쉪?θ㏄?밤?,
    'about-svc3-t':'曆룟릦?잍곭내瀯?,'about-svc3-d':'餓쩉OSBACK?똃octor Reward訝뷰릎恙껓펽瓦욄렏K-獰롥쫮?곩뙸?℡겈佯룝에??곩??룟쪝?긱곩릦鵝쒒뇫?띴퓷?⒵쐨?←쉪曆룟릦亮녑룿?뜻엫??,
    'about-str-label':'?멨퓘鴉섇듌','about-str-title':'?멨퓘 <em>鴉섇듌</em>',
    'about-str-sub':'BIGWAVE3??잒퓹?η풆倻녴곩뙸?쀥겈佯룔곲뇫?띸쭛??꾢량凉귛뙑塋욂틝?쏉펽若욅렟??똻瀯?쥭?욍?,
    'about-str1-h':'?드븚訝롥뙸?㏘에??뭄?곁쉪?뚪뇥瀯볠엫','about-str1-p':'COSBACK??벨?곮눌阿겼뭽也뽩뒻燁?눕?꾣졇恙껃뭄?곤펽Doctor Reward??뙸?㏘에??룓堊쎾뭽?ε볜?방쓢?꾣렏鰲?궧亮녑룿?귚륵訝ゅ뭄?겼릢?ょ떖塋뗨퓧?ο펽鵝녶쑉若€댎鵝볣챿訝?퐳訝뷰?訝よ퓹?η쉪獰롥??묋엻燁묉??잍곭내瀯잒퓧鵝쒌?,
    'about-str2-h':'K-獰롥쫮?곭뎹役곲싧읃簾','about-str2-p':'?싪퓝訝롥쎖?낂쳵塋츺-獰롥쫮?곭뎹?꾣탛?싧룋亮녑룿?붷뒯竊뚦성?뽩읃雅롣벨?곭쉪若€댎凉뺝뀯瀯볠엫?귚툖餓끺퍎堊앲탺亮욕몜竊뚩뚧삸?싪퓝若욇솀雅㎩뱚兀?물?뚥슴?ⓧ퐪謠뚦컛?ⓩ댎饔у뙑訝뷴뭄?겻폏?섅?,
    'about-str3-h':'也뽩뒻楹사퍨?멨뀽?θ칳雅㎪쓢?븀?','about-str3-p':'?뷰틢訝롥뙑倻녶뱚兀?물?멨뀽?꾢쪝?긺㎝榮?룋鵝욜뵪楹사퍨訝볟닶?녑츣竊뚦븚訝싨Æ凉뤸똻瀯?뜃瀛㎯귝돥掠뺜맏弱녻눌阿계죱訝뷴뭽也뽩뒻鵝욜뵪瀯볠엫楹사퍨?뽫쉪亮녑룿???탡雅㎯?,
    'about-ach-label':'訝삭쫨?먨갚','about-ach-title':'訝삭쫨 <em>?먨갚</em>',
    'about-ach-sub':'BIGWAVE3餓η떖?됪???뒟??br>?θ칳雅㎪쓢訝뷴읃簾?쏃졾량凉귛뙑餓룟쇈?,
    'about-pat-h':'?뷰틢訝볟닶?녑츣?꾣???탡雅?,
    'about-pat-p':'訝롥뀶?멩졇恙껃븚訝싨Æ凉뤹쎑?녘걫??strong>?뽩쫮?곮눌阿겼쪝?긺㎝榮?룋鵝욜뵪楹사퍨</strong>竊뚥빳?딂?楹사퍨訝?돢烏뚨쉪也뽩뒻燁?눕?듾슴?ⓩ뼶力뺟쉪訝볟닶?녑츣藥꿱렩簾????,
    'about-pat-note':'瓦쇿컛鵝쒍맏藥?펰?뺺OSBACK?똃octor Reward也뽩뒻瀯볠엫?꾣???풚??뒥餓θ퓧?ⓦ?,
    'about-tag1-t':'?θ칳雅㎪쓢?븀?','about-tag1-s':'簾?퓷?ф쐣???탡雅?,
    'about-tag2-t':'訝싧뒦?뤷릪凉뷴뙑','about-tag2-s':'訝롦졇恙껃븚訝싨Æ凉뤹쎍?θ퓹??,
    'about-tag3-t':'?ゆ씎餓룟쇔닗??,'about-tag3-s':'??똻瀯?쳻雅됦폍??,
    'about-vis-label':'?욘솺','about-vis-title':'BIGWAVE3??<em>?욘솺</em>',
    'about-vis-quote':'<span class="vq-mark">"</span>弱낻-獰롥쫮兀?물鵝볣챿?⒴콝訝?em>也뽩뒻?묋엻鵝볣챿</em>竊?br>瓦욄렏?삯솫岳→겘訝롥겈佯루돶?껆쉪<br>?①릡獰롥??묋엻燁묉?亮녑룿<span class="vq-mark">"</span>',
    'about-vis-desc':'BIGWAVE3?닷뒟雅롨텈擁듿뜒瀛?쉪雅㎩뱚兀?물竊뚧돀?졽?燁띷뼭?꾣텋兀밭퍜?꾟붴붷쑉兀?물瓦뉒쮮訝?㎝榮?돶?껓펽亮뜹컛燁?눕?꾤돶?껈뇥?계퓹?ε댆?ε볜訝롥뙸?㏘에??퐪謠뚣?,
    'about-vis-divider':'BIGWAVE3閭ｅ쑉餓?strong>?경뜮?뚦쪝?긴맏訝?퓘?띷뼭溫얕?</strong>獰롥쫮烏뚥툣?꾥눌阿겻퐪謠뚣?,
    'about-closing-p1':'<strong>COSBACK</strong>兀잒뇩K-獰롥쫮?드븚?꾣돥掠뺞㏆펽<br><strong>Doctor Reward</strong>瓦욄렏?삯솫岳→겘訝롥겈佯룟쪝?긴퐪謠뚣?,
    'about-closing-p2':'?묇뺄弱녺빵瀯?닇?요맏瓦욄렏K-獰롥쫮?곩뙸?쀥겈佯룔곲뇫?띸쭛?訝롥뀲?껅탛?싩쉪?쎿뼭亮녑룿鴉곦툣??,
  }
};

function setLang(lang) {
  document.documentElement.lang = lang === 'zh' ? 'zh-Hans' : lang;
  const t = T[lang];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const v = t[el.dataset.i18n];
    if (v !== undefined) el.innerHTML = v;
  });
  // marquee: duplicate spans
  document.querySelectorAll('.mtrack span').forEach(el => {
    const v = t['marquee'];
    if (v) el.innerHTML = v;
  });
  document.querySelectorAll('.lang-btn').forEach(b =>
    b.classList.toggle('active', b.dataset.lang === lang));
  // ?쒕∼?ㅼ슫 ?몃━嫄??쇰꺼 + 援?린 ?낅뜲?댄듃
  const label = document.getElementById('lang-label');
  const flagEl = document.getElementById('lang-flag');
  const flagCodes = {ko:'kr', en:'us', ja:'jp', zh:'cn'};
  if(label) label.textContent = lang.toUpperCase();
  if(flagEl) flagEl.src = `https://flagcdn.com/20x15/${flagCodes[lang]}.png`;
  document.title = {
    ko:'BIGWAVE3 ???뚮퉬媛 ?먯궛???섎뒗 K-酉고떚??誘몃옒',
    en:'BIGWAVE3 ??The Future of K-Beauty Where Spending Becomes Assets',
    ja:'BIGWAVE3 ??易덅꼇?뚩퀒?ｃ겓?ゃ굥K-?볝깷?쇈깇?ｃ꺖??쑋??,
    zh:'BIGWAVE3 ??易덅뉩?섋탡雅㎫쉪K-獰롥쫮?ゆ씎'
  }[lang];
  localStorage.setItem('bw3-lang', lang);
}

document.addEventListener('DOMContentLoaded', () => {
  const sw = document.getElementById('lang-sw');
  const trigger = document.getElementById('lang-trigger');

  // ?쒕∼?ㅼ슫 ?닿린/?リ린
  if(trigger) {
    trigger.addEventListener('click', e => {
      e.stopPropagation();
      sw.classList.toggle('open');
    });
  }
  // ?몃? ?대┃ ???リ린
  document.addEventListener('click', () => { if(sw) sw.classList.remove('open'); });

  // ?몄뼱 踰꾪듉 ?대┃
  document.querySelectorAll('.lang-btn').forEach(b =>
    b.addEventListener('click', () => {
      setLang(b.dataset.lang);
      if(sw) sw.classList.remove('open');
    }));

  const saved = localStorage.getItem('bw3-lang') || 'ko';
  setLang(saved);
});

