/* BIGWAVE3 — i18n translations  (ko / en / ja / zh) */
const T = {
  ko: {
    /* NAV */
    'nav-cosback':'코스백','nav-dreward':'닥터리워드','nav-member':'정회원',
    'nav-compare':'혜택비교','nav-media':'미디어','nav-cta':'Contact',
    /* HERO */
    'hero-badge':'세계 최초 CosTechMed 뷰티핀테크 생태계',
    'hero-h1':'소비가 자산이 되는<br><em>K-뷰티의 미래</em>',
    'hero-sub':'화장품 소비가 <strong>캐시백</strong>이 되고,<br>시술 리워드가 되고, <strong>안심 보험</strong>이 됩니다.<br>BIGWAVE3는 코스백과 닥터 리워드를 연결해<br>소비가 자산이 되는 K-뷰티 생태계를 만듭니다.',
    'hero-btn1':'정회원 혜택 보기 →','hero-btn2':'코스백 들러보기','hero-btn3':'닥터 리워드 알아보기',
    'hero-plbl':'파트너십',
    /* MARQUEE */
    'marquee':'COSBACK <span class="mstar">★</span> 최대 10% 캐시백 <span class="mstar">★</span> Dr. Reward <span class="mstar">★</span> 병원 1,000개+ <span class="mstar">★</span> Samsung Card iD VITA <span class="mstar">★</span> Samsung Fire 뷰티케어보험 <span class="mstar">★</span> 103개국 글로벌 <span class="mstar">★</span> 2032 회원 목표 600만 명 <span class="mstar">★</span> CosTechMed Platform <span class="mstar">★</span>',
    /* METRICS */
    'sec-metrics-h':'한눈에 보는 BIGWAVE3 <em>핵심 지표</em>',
    'mc1-lbl':'본인 구매 캐시백','mc1-desc':'코스백 입점 브랜드 구매 시 최대 적립',
    'mc2-lbl':'친구 추천 무한 캐시백','mc2-desc':'제휴 삼성카드 결제 시 친구 구매금액 기준',
    'mc3-lbl':'연간 Great Beauty 키트','mc3-desc':'정회원 가입 시 제공되는 연간 혜택 상당액',
    'mc4-lbl':'5년 누적 정회원 가치','mc4-desc':'정회원 유지 시 누적 혜택 추산',
    'mc5-lbl':'파트너 병원 네트워크','mc5-desc':'피부과·성형외과 500개 + 치과·여성의원 500개',
    'mc6-lbl':'글로벌 Language Support','mc6-desc':'2032 회원 목표 600만 명',
    /* CTM */
    'sec-ctm-h':'CosTechMed <em>아키텍처</em>',
    'sec-ctm-lead':'Cosmetics × Technology × Medical — 소비를 자산으로 전환하는 세계 최초 생태계',
    'ctm-cos-h':'일상 소비 플랫폼','ctm-cos-p':'화장품, 건강식품, 패션, 여행 등 고객의 일상 라이프스타일 소비를 코스백 플랫폼에서 통합 관리합니다.',
    'ctm-cos-t1':'화장품','ctm-cos-t2':'건강식품','ctm-cos-t3':'패션·여행',
    'ctm-tech-h':'디지털 연결 레이어','ctm-tech-p':'QR 인증, 앱 연동, 캐시백, 리워드, 보험, 결제 기술 인프라로 소비와 혜택을 실시간 연결합니다.',
    'ctm-tech-t1':'QR·앱','ctm-tech-t2':'캐시백·리워드','ctm-tech-t3':'결제 연동',
    'ctm-med-h':'뷰티 자산화','ctm-med-p':'병원 정보 탐색, 시술 리워드 크레딧, 삼성화재 안심보험 연동으로 소비가 뷰티 자산이 됩니다.',
    'ctm-med-t1':'병원 정보','ctm-med-t2':'시술 리워드','ctm-med-t3':'안심 보험',
    /* COSBACK */
    'sec-cos-h':'COSBACK<br><em>이커머스 플랫폼</em>',
    'sec-cos-lead':'쇼핑할수록 현금이 돌아오는 성과 기반 이커머스 — 캐시백과 닥터 리워드가 연결됩니다.',
    'cof1-lbl':'본인 구매 캐시백','cof1-desc':'코스백 입점 브랜드에서 구매 시 최대 10% 현금성 적립',
    'cof2-lbl':'친구 추천 무한 캐시백','cof2-desc':'추천 링크로 가입한 친구가 구매할 때마다 지속 적립',
    'cof3-lbl':'닥터 리워드 연동','cof3-desc':'제품 QR 스캔 시 뷰티 시술 리워드 자동 연동',
    'cof4-lbl':'카테고리','cof4-desc':'Beauty · Health · Fashion · Travel 전 카테고리',
    'cos-brands-lbl':'입점 브랜드 예시',
    'cos-float1':'이번달 캐시백 적립','cos-float2':'Dr. Reward 리워드 연동',
    /* LOOP */
    'sec-loop-h':'뷰티 <em>자산 루프</em> 고객 여정',
    'sec-loop-lead':'From First Purchase to Infinite Cashback — 10-Step Beauty Asset Journey',
    'ls1':'① 코스백<br>가입','ls2':'② 정회원<br>혜택 활성화','ls3':'③ 브랜드<br>상품 구매','ls4':'④ 캐시백<br>적립','ls5':'⑤ QR<br>스캔',
    'ls6':'⑥ 닥터리워드<br>적립','ls7':'⑦ 병원<br>정보 탐색','ls8':'⑧ 시술 후<br>리워드 활용','ls9':'⑨ 삼성화재<br>보험 연동','ls10':'⑩ 친구추천<br>무한 캐시백',
    'loop-b1':'코스백 캐시백','loop-b2':'닥터 리워드 크레딧','loop-b3':'삼성화재 안심보험','loop-b4':'무한 캐시백 루틴',
    /* SAMSUNG CARD */
    'sec-sc-h':'삼성카드 <em>iD VITA</em><br>협력 금융 루틴',
    'sec-sc-lead':'COSBACK × Samsung Card iD VITA — 고객이 스스로 선택하는 스마트한 정회원 전환 엔진',
    'scf1-t':'병원·약국 혜택','scf1-d':'파트너 병원 및 약국에서 특별 혜택 제공',
    'scf2-t':'생활 영역 혜택','scf2-d':'일상 생활 전반의 카드 혜택',
    'scf3-t':'최대 15% 무한 캐시백','scf3-d':'제휴 삼성카드 결제 시 친구 구매금액의 15%',
    'scf4-t':'삼성화재 보험 연동','scf4-d':'뷰티케어 안심보험 앱에서 실시간 확인',
    'paths-lbl':'정회원 가입 경로',
    'piA-tag':'Path A','piA-t':'현금 납부형','piA-d':'연회비 ₩150,000 직접 납부',
    'piB-tag':'Path B ⭐ Recommended','piB-t':'iD VITA 자발적 가입형','piB-d':'고객 스스로 선택 — 강요 없음',
    'sc-float1-t':'친구 추천 캐시백','sc-float1-s':'제휴 삼성카드 결제 시',
    'sc-float2-t':'뷰티케어 보험','sc-float2-s':'Samsung Fire 연동 완료',
    /* DR REWARD */
    'sec-dr-h':'Dr. Reward<br><em>모바일 플랫폼</em>',
    'drf1-t':'리워드 확인','drf1-d':'코스백 구매·QR 인증·정회원 혜택·친구 추천으로 쌓인 리워드를 앱에서 한눈에 확인',
    'drf2-t':'병원 정보 탐색','drf2-d':'피부과·성형외과·시술 카테고리·지역별 병원 정보 자유 탐색. 고객 자율 선택 — 강제 추천 없음',
    'drf3-t':'시술 후 크레딧 활용','drf3-d':'보유 리워드를 시술 후 결제 단계에서 크레딧처럼 활용',
    'drf4-t':'삼성화재 보험 연동','drf4-d':'앱에서 삼성화재 뷰티케어 안심보험에 바로 가입할 수 있으며, 시술 후 부작용·후유증 리스크를 안전하게 보장받을 수 있습니다',
    'dr-float1-s':'리워드 적립 완료','dr-float2-s':'파트너 병원 네트워크',
    /* GREAT BEAUTY */
    'sec-gb-h':'Great Beauty <em>정회원</em> 멤버십 혜택',
    'sec-gb-lead':'Annual Value ₩500,000 — Premium Beauty Fintech Membership',
    'gb-badge':'연 50만원 상당',
    'gbc1-t':'닥터 리워드 시술 리워드','gbc1-v':'₩300,000 상당','gbc1-d':'피부과·성형외과 파트너 병원에서 활용 가능한 뷰티 리워드 크레딧',
    'gbc2-t':'삼성화재 뷰티케어 안심보험','gbc2-v':'1년 무상 보장','gbc2-d':'시술 후 부작용·후유증 리스크 안전망. BIGWAVE3가 보험료 지원',
    'gbc3-t':'프리미엄 더마 코스메틱 세트','gbc3-v':'₩150,000 상당','gbc3-d':'시술 전후 피부 컨디션 관리를 위한 홈케어 제품. 고객 선택형 혜택',
    'gbc4-t':'무한 캐시백 루틴','gbc4-v':'무제한 적립','gbc4-d':'친구 추천과 코스백 구매를 통한 지속적인 현금성 캐시백 적립',
    'gj-t':'처음에는 무료로 시작하세요','gj-s':'하지만 Great Beauty 혜택은 정회원에게만 열립니다',
    'gjpA':'A형 — 연회비 ₩150,000 납부형','gjpB':'B형 — iD VITA 자발적 가입형 ⭐',
    /* COMPARE */
    'sec-cmp-h':'일반 회원 vs <em>정회원</em> 혜택 비교',
    'ch-gen-lbl':'General Member','ch-gen-t':'일반 회원','ch-gen-sub':'무료 가입',
    'ch-prem-lbl':'Premium Member','ch-prem-t':'정회원','ch-prem-sub':'연회비 또는 연계카드 등록',
    'cr1':'🛍 코스백 구매','cr2':'💰 본인 캐시백','cr3':'👥 친구 추천 캐시백',
    'cr4':'🏥 닥터 리워드','cr5':'🎁 Great Beauty 키트','cr6':'🛡 삼성화재 보험','cr7':'🔗 추천 코드',
    'gen-v1':'가능','gen-v2':'기본 혜택','gen-v3':'제한적','gen-v4':'일부 정보만','gen-v5':'미제공','gen-v6':'미제공','gen-v7':'일반 추천',
    'gen-foot':'체험 고객 · 트래픽 엔진',
    'prem-v1':'최대 혜택 ✓','prem-v2':'최대 10% ✓','prem-v3':'삼성카드 최대 15% 무한 ✓',
    'prem-v4':'시술 리워드 적립·활용 ✓','prem-v5':'연 50만원 상당 ✓','prem-v6':'연동 가능 ✓','prem-v7':'오너십 추천 코드 ✓',
    'prem-foot':'핵심 혜택 고객 · 수익 엔진','prem-cta':'정회원 혜택 활성화하기 →',
    /* DR TV */
    'sec-tv-h':'Dr. Reward TV <em>미디어 센터</em>',
    'sec-tv-lead':'3분이면 이해되는 뷰티핀테크 — 코스백·닥터 리워드·보험·투자까지',
    'tv-main-title':'소비가 자산이 되는 기적,<br>CosTechMed의 시작',
    'tv-it1':'삼성화재 보험 안내','tv-it2':'삼성카드 iD VITA 안내',
    'tv-it3':'고객 인터뷰 — 뷰티 소비가 자산이 된 경험',
    'tv-it4':'피부과 원장 인터뷰 — 의사가 보는 뷰티 리워드',
    'tv-it5':'투자자 인터뷰 — 뷰티핀테크 새로운 시장',
    'tv-more':'전체 영상 보기 →',
    /* FINAL CTA */
    'cta-h2':'BIGWAVE3 생태계에<br><em>지금 합류하세요</em>',
    'cta-p':'고객, 브랜드, 병원, 투자자 모두를 위한 연결이 여기서 시작됩니다',
    'ctac1-t':'고객','ctac1-d':'Great Beauty 정회원이 되어 캐시백, 시술 리워드, 안심 보험 혜택을 시작하세요','ctac1-btn':'정회원 가입하기 →',
    'ctac2-t':'브랜드사','ctac2-d':'광고비 없이 성과 기반으로 고객에게 혜택이 돌아가는 코스백 입점을 시작하세요','ctac2-btn':'브랜드 입점 신청 →',
    'ctac3-t':'파트너 병원','ctac3-d':'고관여 뷰티 고객과 연결되는 닥터 리워드 파트너 병원이 되세요','ctac3-btn':'병원 입점 신청 →',
    'ctac4-t':'투자자','ctac4-d':'CosTechMed 생태계의 성장성과 투자 기회를 확인하세요','ctac4-btn':'IR 자료 요청 →',
    'cta-bottom-p':'소비는 더 이상 사라지는 비용이 아닙니다',
    /* FOOTER */
    'ft-brand-p':'소비가 자산이 되는 세계 최초의 CosTechMed 뷰티핀테크 생태계. COSBACK과 닥터 리워드, 삼성카드·삼성화재가 함께합니다.',
    'ft-l1':'코스백 (COSBACK)','ft-l2':'닥터 리워드','ft-l3':'Great Beauty 정회원','ft-l4':'Dr. Reward TV',
    'ft-l5':'브랜드 입점 신청','ft-l6':'병원 입점 신청','ft-l7':'삼성카드 제휴','ft-l8':'삼성화재 연동',
    'ft-l9':'회사 소개','ft-l10':'IR 자료 요청','ft-l11':'뉴스룸','ft-l12':'이용약관 · 개인정보처리방침',
  },

  en: {
    'nav-cosback':'COSBACK','nav-dreward':'Dr. Reward','nav-member':'Premium',
    'nav-compare':'Compare','nav-media':'Media','nav-cta':'Request IR',
    'hero-badge':'World\'s First CosTechMed Beauty Fintech Ecosystem',
    'hero-h1':'Where Spending Becomes<br><em>The Future of K-Beauty</em>',
    'hero-sub':'Cosmetics spending becomes <strong>cashback</strong>,<br>treatment rewards, and <strong>peace-of-mind insurance</strong>.<br>BIGWAVE3 connects COSBACK &amp; Dr. Reward<br>to build a K-Beauty ecosystem where spending becomes assets.',
    'hero-btn1':'See Premium Benefits →','hero-btn2':'Explore COSBACK','hero-btn3':'Learn Dr. Reward',
    'hero-plbl':'Partnership',
    'marquee':'COSBACK <span class="mstar">★</span> Up to 10% Cashback <span class="mstar">★</span> Dr. Reward <span class="mstar">★</span> 1,000+ Clinics <span class="mstar">★</span> Samsung Card iD VITA <span class="mstar">★</span> Samsung Fire Beauty Insurance <span class="mstar">★</span> 103 Countries <span class="mstar">★</span> 6M Members Goal by 2032 <span class="mstar">★</span> CosTechMed Platform <span class="mstar">★</span>',
    'sec-metrics-h':'BIGWAVE3 <em>Key Metrics</em> at a Glance',
    'mc1-lbl':'Personal Purchase Cashback','mc1-desc':'Up to 10% on every COSBACK brand purchase',
    'mc2-lbl':'Infinite Friend Referral','mc2-desc':'Earn every time your referred friend shops with Samsung Card',
    'mc3-lbl':'Annual Great Beauty Kit','mc3-desc':'Estimated annual benefit value for premium members',
    'mc4-lbl':'5-Year Member Value','mc4-desc':'Cumulative estimated benefit over 5 years of membership',
    'mc5-lbl':'Partner Clinic Network','mc5-desc':'500 dermatology & plastic surgery + 500 dental & women\'s clinics',
    'mc6-lbl':'Global Language Support','mc6-desc':'Target 6M members by 2032',
    'sec-ctm-h':'CosTechMed <em>Architecture</em>',
    'sec-ctm-lead':'Cosmetics × Technology × Medical — The world\'s first ecosystem turning spending into assets',
    'ctm-cos-h':'Everyday Spending Platform','ctm-cos-p':'Manage all lifestyle spending — cosmetics, health, fashion, travel — in one unified COSBACK platform.',
    'ctm-cos-t1':'Cosmetics','ctm-cos-t2':'Health Food','ctm-cos-t3':'Fashion · Travel',
    'ctm-tech-h':'Digital Connection Layer','ctm-tech-p':'QR, app integration, cashback, rewards, insurance, and payment infrastructure — connecting spending to benefits in real time.',
    'ctm-tech-t1':'QR · App','ctm-tech-t2':'Cashback · Rewards','ctm-tech-t3':'Payment Link',
    'ctm-med-h':'Beauty Asset Return','ctm-med-p':'Clinic discovery, treatment reward credits, and Samsung Fire insurance integration turn spending into beauty assets.',
    'ctm-med-t1':'Clinic Info','ctm-med-t2':'Treatment Rewards','ctm-med-t3':'Peace-of-Mind Insurance',
    'sec-cos-h':'COSBACK<br><em>E-Commerce Platform</em>',
    'sec-cos-lead':'Performance-based e-commerce where every purchase pays you back — cashback meets Dr. Reward.',
    'cof1-lbl':'Personal Cashback','cof1-desc':'Up to 10% cash reward on every COSBACK brand purchase',
    'cof2-lbl':'Infinite Friend Referral','cof2-desc':'Earn every time a referred friend makes a purchase',
    'cof3-lbl':'Dr. Reward Integration','cof3-desc':'Scan product QR to automatically earn beauty treatment rewards',
    'cof4-lbl':'Categories','cof4-desc':'Beauty · Health · Fashion · Travel — all categories',
    'cos-brands-lbl':'Partner Brand Examples',
    'cos-float1':'Cashback this month','cos-float2':'Dr. Reward Connected',
    'sec-loop-h':'Beauty <em>Asset Loop</em> Customer Journey',
    'sec-loop-lead':'From First Purchase to Infinite Cashback — 10-Step Beauty Asset Journey',
    'ls1':'① Join<br>COSBACK','ls2':'② Activate<br>Premium','ls3':'③ Buy<br>Brands','ls4':'④ Earn<br>Cashback','ls5':'⑤ Scan<br>QR',
    'ls6':'⑥ Earn<br>Dr. Reward','ls7':'⑦ Explore<br>Clinics','ls8':'⑧ Use Reward<br>Post-Treatment','ls9':'⑨ Samsung Fire<br>Insurance','ls10':'⑩ Infinite<br>Friend Referral',
    'loop-b1':'COSBACK Cashback','loop-b2':'Dr. Reward Credit','loop-b3':'Samsung Fire Insurance','loop-b4':'Infinite Cashback Loop',
    'sec-sc-h':'Samsung Card <em>iD VITA</em><br>Partnership',
    'sec-sc-lead':'COSBACK × Samsung Card iD VITA — A smart premium membership engine chosen by customers themselves',
    'scf1-t':'Clinic & Pharmacy Benefits','scf1-d':'Special benefits at partner clinics and pharmacies',
    'scf2-t':'Everyday Life Benefits','scf2-d':'Card benefits across all areas of daily life',
    'scf3-t':'Up to 15% Infinite Cashback','scf3-d':'15% on friends\' purchases when paying with partner Samsung Card',
    'scf4-t':'Samsung Fire Integration','scf4-d':'Check beauty care insurance status in real time via app',
    'paths-lbl':'Premium Membership Paths',
    'piA-tag':'Path A','piA-t':'Direct Payment','piA-d':'Pay ₩150,000 annual fee directly',
    'piB-tag':'Path B ⭐ Recommended','piB-t':'iD VITA Voluntary Sign-up','piB-d':'Customer\'s own choice — no pressure',
    'sc-float1-t':'Friend Referral Cashback','sc-float1-s':'Via partner Samsung Card',
    'sc-float2-t':'Beauty Care Insurance','sc-float2-s':'Samsung Fire linked',
    'sec-dr-h':'Dr. Reward<br><em>Mobile Platform</em>',
    'drf1-t':'Check Rewards','drf1-d':'See all rewards earned from purchases, QR scans, premium benefits, and referrals in one view',
    'drf2-t':'Explore Clinics','drf2-d':'Browse dermatology, plastic surgery, and treatment categories by region. Customer\'s free choice — no forced recommendations',
    'drf3-t':'Use Credits Post-Treatment','drf3-d':'Apply accumulated rewards as credits at the payment stage after treatment',
    'drf4-t':'Insurance Status','drf4-d':'Check Samsung Fire beauty care insurance link status in real time',
    'dr-float1-s':'Reward earned','dr-float2-s':'Partner Clinic Network',
    'sec-gb-h':'Great Beauty <em>Premium</em> Membership Benefits',
    'sec-gb-lead':'Annual Value ₩500,000 — Premium Beauty Fintech Membership',
    'gb-badge':'₩500K Annual Value',
    'gbc1-t':'Dr. Reward Treatment Credit','gbc1-v':'Worth ₩300,000','gbc1-d':'Beauty reward credit usable at partner dermatology & plastic surgery clinics',
    'gbc2-t':'Samsung Fire Beauty Insurance','gbc2-v':'1 Year Free Coverage','gbc2-d':'Safety net for side effects after treatment. BIGWAVE3 covers the premium',
    'gbc3-t':'Premium Derma Cosmetic Set','gbc3-v':'Worth ₩150,000','gbc3-d':'Home-care products for skin condition before and after treatment. Customer\'s choice',
    'gbc4-t':'Infinite Cashback Routine','gbc4-v':'Unlimited','gbc4-d':'Continuous cash-equivalent cashback via friend referrals and COSBACK purchases',
    'gj-t':'Start free today','gj-s':'But Great Beauty benefits are exclusive to premium members',
    'gjpA':'Path A — ₩150,000 Annual Fee','gjpB':'Path B — iD VITA Voluntary ⭐',
    'sec-cmp-h':'General vs <em>Premium</em> Membership Comparison',
    'ch-gen-lbl':'General Member','ch-gen-t':'General','ch-gen-sub':'Free',
    'ch-prem-lbl':'Premium Member','ch-prem-t':'Premium','ch-prem-sub':'Annual fee or partner card',
    'cr1':'🛍 COSBACK Shopping','cr2':'💰 Personal Cashback','cr3':'👥 Friend Referral',
    'cr4':'🏥 Dr. Reward','cr5':'🎁 Great Beauty Kit','cr6':'🛡 Samsung Fire Insurance','cr7':'🔗 Referral Code',
    'gen-v1':'Available','gen-v2':'Basic','gen-v3':'Limited','gen-v4':'Partial info','gen-v5':'Not included','gen-v6':'Not included','gen-v7':'Standard',
    'gen-foot':'Trial users · Traffic engine',
    'prem-v1':'Max benefits ✓','prem-v2':'Up to 10% ✓','prem-v3':'Samsung Card up to 15% infinite ✓',
    'prem-v4':'Earn & use treatment rewards ✓','prem-v5':'₩500K annual value ✓','prem-v6':'Linked ✓','prem-v7':'Ownership referral code ✓',
    'prem-foot':'Core benefit users · Revenue engine','prem-cta':'Activate Premium Benefits →',
    'sec-tv-h':'Dr. Reward TV <em>Media Center</em>',
    'sec-tv-lead':'Understand beauty fintech in 3 minutes — COSBACK, Dr. Reward, insurance, investing',
    'tv-main-title':'The miracle of spending becoming assets —<br>The beginning of CosTechMed',
    'tv-it1':'Samsung Fire Insurance Guide','tv-it2':'Samsung Card iD VITA Guide',
    'tv-it3':'Customer Interview — How spending became an asset','tv-it4':'Dermatologist Interview — A doctor\'s view on beauty rewards',
    'tv-it5':'Investor Interview — The new beauty fintech market',
    'tv-more':'View All Videos →',
    'cta-h2':'Join the BIGWAVE3<br><em>Ecosystem Now</em>',
    'cta-p':'Connections for customers, brands, clinics, and investors all start here',
    'ctac1-t':'Customers','ctac1-d':'Become a Great Beauty premium member and start earning cashback, treatment rewards, and insurance','ctac1-btn':'Join Premium →',
    'ctac2-t':'Brands','ctac2-d':'List on COSBACK — performance-based benefits with no ad spend','ctac2-btn':'List Your Brand →',
    'ctac3-t':'Clinics','ctac3-d':'Become a Dr. Reward partner clinic and connect with high-intent beauty customers','ctac3-btn':'Partner With Us →',
    'ctac4-t':'Investors','ctac4-d':'Explore the growth potential and investment opportunity in the CosTechMed ecosystem','ctac4-btn':'Request IR Materials →',
    'cta-bottom-p':'Spending is no longer a cost that disappears',
    'ft-brand-p':'The world\'s first CosTechMed beauty fintech ecosystem where spending becomes assets. With COSBACK, Dr. Reward, Samsung Card & Samsung Fire.',
    'ft-l1':'COSBACK','ft-l2':'Dr. Reward','ft-l3':'Great Beauty Premium','ft-l4':'Dr. Reward TV',
    'ft-l5':'Brand Listing','ft-l6':'Clinic Listing','ft-l7':'Samsung Card Partnership','ft-l8':'Samsung Fire Link',
    'ft-l9':'About Us','ft-l10':'IR Materials','ft-l11':'Newsroom','ft-l12':'Terms · Privacy Policy',
  },

  ja: {
    'nav-cosback':'コスバック','nav-dreward':'Dr.リワード','nav-member':'プレミアム',
    'nav-compare':'特典比較','nav-media':'メディア','nav-cta':'IR資料請求',
    'hero-badge':'世界初 CosTechMed 美容フィンテックエコシステム',
    'hero-h1':'消費が資産になる<br><em>K-ビューティーの未来</em>',
    'hero-sub':'化粧品の消費が<strong>キャッシュバック</strong>になり、<br>施術リワードになり、<strong>安心保険</strong>になります。<br>BIGWAVE3はコスバックとDr.リワードを繋ぎ、<br>消費が資産になるK-ビューティーエコシステムを作ります。',
    'hero-btn1':'プレミアム特典を見る →','hero-btn2':'コスバックを見る','hero-btn3':'Dr.リワードを知る',
    'hero-plbl':'パートナーシップ',
    'marquee':'COSBACK <span class="mstar">★</span> 最大10%キャッシュバック <span class="mstar">★</span> Dr.リワード <span class="mstar">★</span> 提携クリニック1,000院+ <span class="mstar">★</span> Samsung Card iD VITA <span class="mstar">★</span> Samsung Fire 美容ケア保険 <span class="mstar">★</span> 103カ国グローバル <span class="mstar">★</span> 2032年会員600万人目標 <span class="mstar">★</span> CosTechMed Platform <span class="mstar">★</span>',
    'sec-metrics-h':'BIGWAVE3 <em>主要指標</em>一覧',
    'mc1-lbl':'本人購入キャッシュバック','mc1-desc':'コスバック入店ブランド購入時に最大積立',
    'mc2-lbl':'友達紹介無限キャッシュバック','mc2-desc':'提携サムスンカード決済時に友達購入額基準',
    'mc3-lbl':'年間グレートビューティーキット','mc3-desc':'プレミアム会員加入時の年間特典相当額',
    'mc4-lbl':'5年累計プレミアム価値','mc4-desc':'プレミアム会員維持時の累計特典推算',
    'mc5-lbl':'パートナークリニックネットワーク','mc5-desc':'皮膚科・形成外科500院 + 歯科・婦人科500院',
    'mc6-lbl':'グローバル言語サポート','mc6-desc':'2032年会員目標600万人',
    'sec-ctm-h':'CosTechMed <em>アーキテクチャ</em>',
    'sec-ctm-lead':'Cosmetics × Technology × Medical — 消費を資産に変換する世界初のエコシステム',
    'ctm-cos-h':'日常消費プラットフォーム','ctm-cos-p':'化粧品・健康食品・ファッション・旅行など日常のライフスタイル消費をコスバックで一元管理。',
    'ctm-cos-t1':'化粧品','ctm-cos-t2':'健康食品','ctm-cos-t3':'ファッション・旅行',
    'ctm-tech-h':'デジタル接続レイヤー','ctm-tech-p':'QR認証・アプリ連携・キャッシュバック・リワード・保険・決済インフラで消費と特典をリアルタイム接続。',
    'ctm-tech-t1':'QR・アプリ','ctm-tech-t2':'キャッシュバック・リワード','ctm-tech-t3':'決済連携',
    'ctm-med-h':'美容資産化','ctm-med-p':'クリニック情報・施術リワードクレジット・Samsung Fire安心保険連携で消費が美容資産に。',
    'ctm-med-t1':'クリニック情報','ctm-med-t2':'施術リワード','ctm-med-t3':'安心保険',
    'sec-cos-h':'コスバック<br><em>ECプラットフォーム</em>',
    'sec-cos-lead':'買うたびに現金が還ってくる成果型EC — キャッシュバックとDr.リワードが繋がります。',
    'cof1-lbl':'本人購入キャッシュバック','cof1-desc':'コスバック入店ブランドで購入時最大10%現金積立',
    'cof2-lbl':'友達紹介無限キャッシュバック','cof2-desc':'紹介リンクから加入した友達が購入するたびに積立',
    'cof3-lbl':'Dr.リワード連携','cof3-desc':'商品QRスキャンで美容施術リワードが自動連携',
    'cof4-lbl':'カテゴリー','cof4-desc':'Beauty · Health · Fashion · Travel 全カテゴリー',
    'cos-brands-lbl':'入店ブランド例',
    'cos-float1':'今月のキャッシュバック積立','cos-float2':'Dr.リワード連携済み',
    'sec-loop-h':'美容 <em>資産ループ</em> カスタマージャーニー',
    'sec-loop-lead':'From First Purchase to Infinite Cashback — 10-Step Beauty Asset Journey',
    'ls1':'① コスバック<br>加入','ls2':'② プレミアム<br>特典有効化','ls3':'③ ブランド<br>商品購入','ls4':'④ キャッシュ<br>バック積立','ls5':'⑤ QR<br>スキャン',
    'ls6':'⑥ Dr.リワード<br>積立','ls7':'⑦ クリニック<br>情報探索','ls8':'⑧ 施術後<br>リワード活用','ls9':'⑨ Samsung Fire<br>保険連携','ls10':'⑩ 友達紹介<br>無限キャッシュバック',
    'loop-b1':'コスバック キャッシュバック','loop-b2':'Dr.リワード クレジット','loop-b3':'Samsung Fire 安心保険','loop-b4':'無限キャッシュバックルーティン',
    'sec-sc-h':'Samsung Card <em>iD VITA</em><br>提携金融ルーティン',
    'sec-sc-lead':'COSBACK × Samsung Card iD VITA — お客様が自ら選ぶスマートなプレミアム転換エンジン',
    'scf1-t':'クリニック・薬局特典','scf1-d':'パートナークリニック・薬局での特別特典',
    'scf2-t':'生活領域特典','scf2-d':'日常生活全般のカード特典',
    'scf3-t':'最大15%無限キャッシュバック','scf3-d':'提携サムスンカード決済時に友達購入額の15%',
    'scf4-t':'Samsung Fire 保険連携','scf4-d':'美容ケア安心保険をアプリでリアルタイム確認',
    'paths-lbl':'プレミアム会員加入経路',
    'piA-tag':'Path A','piA-t':'現金支払型','piA-d':'年会費 ₩150,000 直接支払',
    'piB-tag':'Path B ⭐ おすすめ','piB-t':'iD VITA 自発的加入型','piB-d':'お客様の自由な選択 — 強制なし',
    'sc-float1-t':'友達紹介キャッシュバック','sc-float1-s':'提携サムスンカード決済時',
    'sc-float2-t':'美容ケア保険','sc-float2-s':'Samsung Fire 連携完了',
    'sec-dr-h':'Dr. Reward<br><em>モバイルプラットフォーム</em>',
    'drf1-t':'リワード確認','drf1-d':'購入・QRスキャン・プレミアム特典・友達紹介で貯まったリワードをアプリで一覧確認',
    'drf2-t':'クリニック情報探索','drf2-d':'皮膚科・形成外科・施術カテゴリー・地域別クリニック情報を自由に探索。強制推薦なし',
    'drf3-t':'施術後クレジット活用','drf3-d':'保有リワードを施術後の決済段階でクレジットとして活用',
    'drf4-t':'保険状態確認','drf4-d':'Samsung Fire 美容ケア安心保険の連携状態をアプリでリアルタイム確認',
    'dr-float1-s':'リワード積立完了','dr-float2-s':'パートナークリニックネットワーク',
    'sec-gb-h':'グレートビューティー <em>プレミアム</em> 会員特典',
    'sec-gb-lead':'年間価値 ₩500,000 — プレミアム美容フィンテック会員',
    'gb-badge':'年50万ウォン相当',
    'gbc1-t':'Dr.リワード 施術リワード','gbc1-v':'₩300,000相当','gbc1-d':'パートナー皮膚科・形成外科で使える美容リワードクレジット',
    'gbc2-t':'Samsung Fire 美容ケア安心保険','gbc2-v':'1年無償保障','gbc2-d':'施術後の副作用・後遺症リスクのセーフティネット。BIGWAVE3が保険料を支援',
    'gbc3-t':'プレミアムダーマコスメセット','gbc3-v':'₩150,000相当','gbc3-d':'施術前後の肌コンディション管理のためのホームケア製品',
    'gbc4-t':'無限キャッシュバックルーティン','gbc4-v':'無制限積立','gbc4-d':'友達紹介とコスバック購入による継続的な現金キャッシュバック',
    'gj-t':'まず無料で始めましょう','gj-s':'グレートビューティー特典はプレミアム会員限定です',
    'gjpA':'A型 — 年会費 ₩150,000 支払型','gjpB':'B型 — iD VITA 自発的加入型 ⭐',
    'sec-cmp-h':'一般会員 vs <em>プレミアム会員</em> 特典比較',
    'ch-gen-lbl':'General Member','ch-gen-t':'一般会員','ch-gen-sub':'無料加入',
    'ch-prem-lbl':'Premium Member','ch-prem-t':'プレミアム会員','ch-prem-sub':'年会費または提携カード登録',
    'cr1':'🛍 コスバック購入','cr2':'💰 本人キャッシュバック','cr3':'👥 友達紹介キャッシュバック',
    'cr4':'🏥 Dr.リワード','cr5':'🎁 グレートビューティーキット','cr6':'🛡 Samsung Fire 保険','cr7':'🔗 紹介コード',
    'gen-v1':'可能','gen-v2':'基本特典','gen-v3':'制限あり','gen-v4':'一部情報のみ','gen-v5':'非提供','gen-v6':'非提供','gen-v7':'通常紹介',
    'gen-foot':'体験顧客 · トラフィックエンジン',
    'prem-v1':'最大特典 ✓','prem-v2':'最大10% ✓','prem-v3':'サムスンカード最大15%無限 ✓',
    'prem-v4':'施術リワード積立・活用 ✓','prem-v5':'年50万ウォン相当 ✓','prem-v6':'連携可能 ✓','prem-v7':'オーナーシップ紹介コード ✓',
    'prem-foot':'コア特典顧客 · 収益エンジン','prem-cta':'プレミアム特典を有効化する →',
    'sec-tv-h':'Dr. Reward TV <em>メディアセンター</em>',
    'sec-tv-lead':'3分でわかる美容フィンテック — コスバック・Dr.リワード・保険・投資まで',
    'tv-main-title':'消費が資産になる奇跡、<br>CosTechMedの始まり',
    'tv-it1':'Samsung Fire 保険案内','tv-it2':'Samsung Card iD VITA 案内',
    'tv-it3':'顧客インタビュー — 消費が資産になった体験','tv-it4':'皮膚科院長インタビュー — 医師が見る美容リワード',
    'tv-it5':'投資家インタビュー — 美容フィンテック新市場',
    'tv-more':'全動画を見る →',
    'cta-h2':'BIGWAVE3 エコシステムに<br><em>今すぐ参加</em>',
    'cta-p':'顧客・ブランド・クリニック・投資家すべてのための繋がりがここから始まります',
    'ctac1-t':'顧客','ctac1-d':'グレートビューティープレミアム会員になってキャッシュバック・施術リワード・安心保険を始めよう','ctac1-btn':'プレミアム加入 →',
    'ctac2-t':'ブランド','ctac2-d':'広告費なしで成果ベースで顧客に特典が還るコスバックへの入店を始めよう','ctac2-btn':'ブランド入店申請 →',
    'ctac3-t':'パートナークリニック','ctac3-d':'高関与の美容顧客と繋がるDr.リワードパートナークリニックになろう','ctac3-btn':'クリニック申請 →',
    'ctac4-t':'投資家','ctac4-d':'CosTechMedエコシステムの成長性と投資機会をご確認ください','ctac4-btn':'IR資料請求 →',
    'cta-bottom-p':'消費はもはや消えていくコストではありません',
    'ft-brand-p':'消費が資産になる世界初のCosTechMed美容フィンテックエコシステム。COSBACKとDr.リワード、Samsung Card・Samsung Fireが共にあります。',
    'ft-l1':'コスバック (COSBACK)','ft-l2':'Dr.リワード','ft-l3':'グレートビューティープレミアム','ft-l4':'Dr. Reward TV',
    'ft-l5':'ブランド入店申請','ft-l6':'クリニック入店申請','ft-l7':'Samsung Card 提携','ft-l8':'Samsung Fire 連携',
    'ft-l9':'会社紹介','ft-l10':'IR資料請求','ft-l11':'ニュースルーム','ft-l12':'利用規約 · プライバシーポリシー',
  },

  zh: {
    'nav-cosback':'返现购物','nav-dreward':'博士奖励','nav-member':'高级会员',
    'nav-compare':'权益比较','nav-media':'媒体','nav-cta':'申请IR资料',
    'hero-badge':'全球首个 CosTechMed 美容金融科技生态系统',
    'hero-h1':'消费变资产的<br><em>K-美妆未来</em>',
    'hero-sub':'化妆品消费变成<strong>返现</strong>，<br>变成美容奖励，变成<strong>安心保险</strong>。<br>BIGWAVE3连接COSBACK和博士奖励，<br>构建消费变资产的K-美妆生态系统。',
    'hero-btn1':'查看高级会员权益 →','hero-btn2':'探索COSBACK','hero-btn3':'了解博士奖励',
    'hero-plbl':'合作伙伴',
    'marquee':'COSBACK <span class="mstar">★</span> 最高10%返现 <span class="mstar">★</span> 博士奖励 <span class="mstar">★</span> 合作医院1,000家+ <span class="mstar">★</span> Samsung Card iD VITA <span class="mstar">★</span> Samsung Fire 美容保险 <span class="mstar">★</span> 全球103国 <span class="mstar">★</span> 2032年目标600万会员 <span class="mstar">★</span> CosTechMed Platform <span class="mstar">★</span>',
    'sec-metrics-h':'BIGWAVE3 <em>核心指标</em>一览',
    'mc1-lbl':'本人购买返现','mc1-desc':'购买COSBACK入驻品牌最高积累',
    'mc2-lbl':'好友推荐无限返现','mc2-desc':'使用联名三星卡结算时按好友购买金额计算',
    'mc3-lbl':'年度美丽礼包','mc3-desc':'高级会员加入时提供的年度权益相当金额',
    'mc4-lbl':'5年累计会员价值','mc4-desc':'保持高级会员时的累计权益估算',
    'mc5-lbl':'合作医院网络','mc5-desc':'皮肤科·整形外科500家 + 牙科·妇科500家',
    'mc6-lbl':'全球语言支持','mc6-desc':'2032年会员目标600万人',
    'sec-ctm-h':'CosTechMed <em>架构</em>',
    'sec-ctm-lead':'化妆品 × 技术 × 医疗 — 全球首个将消费转化为资产的生态系统',
    'ctm-cos-h':'日常消费平台','ctm-cos-p':'化妆品、健康食品、时尚、旅行等日常生活消费在COSBACK平台统一管理。',
    'ctm-cos-t1':'化妆品','ctm-cos-t2':'健康食品','ctm-cos-t3':'时尚·旅行',
    'ctm-tech-h':'数字连接层','ctm-tech-p':'QR认证、App联动、返现、奖励、保险、支付技术基础设施实时连接消费与权益。',
    'ctm-tech-t1':'QR·App','ctm-tech-t2':'返现·奖励','ctm-tech-t3':'支付联动',
    'ctm-med-h':'美容资产化','ctm-med-p':'医院信息探索、医美奖励积分、三星火灾安心保险联动，让消费成为美容资产。',
    'ctm-med-t1':'医院信息','ctm-med-t2':'医美奖励','ctm-med-t3':'安心保险',
    'sec-cos-h':'COSBACK<br><em>电商平台</em>',
    'sec-cos-lead':'越购物越返现的绩效型电商 — 返现与博士奖励双重连接。',
    'cof1-lbl':'本人购买返现','cof1-desc':'购买COSBACK入驻品牌最高10%现金积累',
    'cof2-lbl':'好友推荐无限返现','cof2-desc':'通过推荐链接加入的好友每次购买都持续积累',
    'cof3-lbl':'博士奖励联动','cof3-desc':'扫描商品QR自动联动美容医美奖励',
    'cof4-lbl':'品类','cof4-desc':'美妆·健康·时尚·旅行 全品类',
    'cos-brands-lbl':'入驻品牌示例',
    'cos-float1':'本月返现积累','cos-float2':'博士奖励已连接',
    'sec-loop-h':'美容 <em>资产循环</em> 客户旅程',
    'sec-loop-lead':'从首次购买到无限返现 — 10步美容资产旅程',
    'ls1':'① 加入<br>COSBACK','ls2':'② 激活<br>高级会员','ls3':'③ 购买<br>品牌商品','ls4':'④ 积累<br>返现','ls5':'⑤ 扫描<br>QR',
    'ls6':'⑥ 积累<br>博士奖励','ls7':'⑦ 探索<br>医院信息','ls8':'⑧ 医美后<br>使用奖励','ls9':'⑨ 三星火灾<br>保险联动','ls10':'⑩ 好友推荐<br>无限返现',
    'loop-b1':'COSBACK返现','loop-b2':'博士奖励积分','loop-b3':'三星火灾安心保险','loop-b4':'无限返现循环',
    'sec-sc-h':'Samsung Card <em>iD VITA</em><br>联名金融方案',
    'sec-sc-lead':'COSBACK × Samsung Card iD VITA — 客户自主选择的智能高级会员转化引擎',
    'scf1-t':'医院·药房权益','scf1-d':'在合作医院及药房享受特别优惠',
    'scf2-t':'生活领域权益','scf2-d':'日常生活全方位刷卡权益',
    'scf3-t':'最高15%无限返现','scf3-d':'使用联名三星卡结算时获得好友购买金额的15%',
    'scf4-t':'三星火灾保险联动','scf4-d':'在App中实时查看美容护理安心保险联动状态',
    'paths-lbl':'高级会员加入路径',
    'piA-tag':'路径A','piA-t':'现金缴费型','piA-d':'直接缴纳年费 ₩150,000',
    'piB-tag':'路径B ⭐ 推荐','piB-t':'iD VITA 自愿加入型','piB-d':'客户自主选择 — 无强制',
    'sc-float1-t':'好友推荐返现','sc-float1-s':'使用联名三星卡结算时',
    'sc-float2-t':'美容护理保险','sc-float2-s':'三星火灾联动完成',
    'sec-dr-h':'Dr. Reward<br><em>移动端平台</em>',
    'drf1-t':'查看奖励','drf1-d':'在App中一览购买、QR扫描、高级会员权益、好友推荐积累的所有奖励',
    'drf2-t':'探索医院信息','drf2-d':'按皮肤科·整形外科·医美类别·地区自由浏览医院信息。客户自主选择，无强制推荐',
    'drf3-t':'医美后使用积分','drf3-d':'在医美后结算阶段将持有奖励作为积分使用',
    'drf4-t':'保险状态查询','drf4-d':'在App中实时查看三星火灾美容护理安心保险联动状态',
    'dr-float1-s':'奖励积累完成','dr-float2-s':'合作医院网络',
    'sec-gb-h':'美丽礼遇 <em>高级会员</em> 专属权益',
    'sec-gb-lead':'年度价值 ₩500,000 — 高级美容金融科技会员',
    'gb-badge':'年度价值50万韩元',
    'gbc1-t':'博士奖励 医美积分','gbc1-v':'价值₩300,000','gbc1-d':'可在合作皮肤科·整形外科使用的美容奖励积分',
    'gbc2-t':'三星火灾 美容安心保险','gbc2-v':'1年免费保障','gbc2-d':'医美后副作用·后遗症风险安全网。BIGWAVE3支付保费',
    'gbc3-t':'高级护肤品套装','gbc3-v':'价值₩150,000','gbc3-d':'医美前后肌肤状态管理的家用护肤产品',
    'gbc4-t':'无限返现循环','gbc4-v':'无限积累','gbc4-d':'通过好友推荐和COSBACK购物持续获得现金返现',
    'gj-t':'先从免费开始','gj-s':'但美丽礼遇特权仅对高级会员开放',
    'gjpA':'A型 — 年费₩150,000 缴费型','gjpB':'B型 — iD VITA 自愿加入型 ⭐',
    'sec-cmp-h':'普通会员 vs <em>高级会员</em> 权益对比',
    'ch-gen-lbl':'普通会员','ch-gen-t':'普通会员','ch-gen-sub':'免费加入',
    'ch-prem-lbl':'高级会员','ch-prem-t':'高级会员','ch-prem-sub':'年费或联名卡注册',
    'cr1':'🛍 COSBACK购物','cr2':'💰 本人返现','cr3':'👥 好友推荐返现',
    'cr4':'🏥 博士奖励','cr5':'🎁 美丽礼包','cr6':'🛡 三星火灾保险','cr7':'🔗 推荐码',
    'gen-v1':'可用','gen-v2':'基础权益','gen-v3':'受限','gen-v4':'部分信息','gen-v5':'不提供','gen-v6':'不提供','gen-v7':'普通推荐',
    'gen-foot':'体验用户 · 流量引擎',
    'prem-v1':'最大权益 ✓','prem-v2':'最高10% ✓','prem-v3':'三星卡最高15%无限 ✓',
    'prem-v4':'医美奖励积累·使用 ✓','prem-v5':'年度价值50万韩元 ✓','prem-v6':'可联动 ✓','prem-v7':'专属推荐码 ✓',
    'prem-foot':'核心权益用户 · 收益引擎','prem-cta':'激活高级会员权益 →',
    'sec-tv-h':'Dr. Reward TV <em>媒体中心</em>',
    'sec-tv-lead':'3分钟读懂美容金融科技 — COSBACK、博士奖励、保险、投资全解析',
    'tv-main-title':'消费变资产的奇迹，<br>CosTechMed的开始',
    'tv-it1':'三星火灾保险介绍','tv-it2':'Samsung Card iD VITA 介绍',
    'tv-it3':'客户访谈 — 消费变资产的亲身体验','tv-it4':'皮肤科院长访谈 — 医生视角下的美容奖励',
    'tv-it5':'投资者访谈 — 美容金融科技新市场',
    'tv-more':'查看全部视频 →',
    'cta-h2':'加入BIGWAVE3<br><em>生态系统</em>',
    'cta-p':'为客户、品牌、医院、投资者提供的连接从这里开始',
    'ctac1-t':'客户','ctac1-d':'成为美丽礼遇高级会员，开始享受返现、医美奖励和安心保险','ctac1-btn':'加入高级会员 →',
    'ctac2-t':'品牌商','ctac2-d':'无需广告费，以绩效为基础让客户获得回报的COSBACK入驻','ctac2-btn':'品牌入驻申请 →',
    'ctac3-t':'合作医院','ctac3-d':'成为博士奖励合作医院，与高意向美容客户建立连接','ctac3-btn':'医院入驻申请 →',
    'ctac4-t':'投资者','ctac4-d':'了解CosTechMed生态系统的成长潜力与投资机会','ctac4-btn':'申请IR资料 →',
    'cta-bottom-p':'消费不再是消失的成本',
    'ft-brand-p':'全球首个消费变资产的CosTechMed美容金融科技生态系统。COSBACK与博士奖励，三星卡·三星火灾共同参与。',
    'ft-l1':'COSBACK返现','ft-l2':'博士奖励','ft-l3':'美丽礼遇高级会员','ft-l4':'Dr. Reward TV',
    'ft-l5':'品牌入驻申请','ft-l6':'医院入驻申请','ft-l7':'三星卡联名','ft-l8':'三星火灾联动',
    'ft-l9':'公司介绍','ft-l10':'IR资料申请','ft-l11':'新闻室','ft-l12':'使用条款 · 隐私政策',
  }
};

function setLang(lang) {
  document.documentElement.lang = lang === 'zh' ? 'zh-Hans' : lang;
  const t = T[lang];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const v = t[el.dataset.i18n];
    if (v !== undefined) el.innerHTML = v;
  });
  // marquee: duplicate spans
  document.querySelectorAll('.mtrack span').forEach(el => {
    const v = t['marquee'];
    if (v) el.innerHTML = v;
  });
  document.querySelectorAll('.lang-btn').forEach(b =>
    b.classList.toggle('active', b.dataset.lang === lang));
  // 드롭다운 트리거 라벨 + 국기 업데이트
  const label = document.getElementById('lang-label');
  const flagEl = document.getElementById('lang-flag');
  const flagCodes = {ko:'kr', en:'us', ja:'jp', zh:'cn'};
  if(label) label.textContent = lang.toUpperCase();
  if(flagEl) flagEl.src = `https://flagcdn.com/20x15/${flagCodes[lang]}.png`;
  document.title = {
    ko:'BIGWAVE3 — 소비가 자산이 되는 K-뷰티의 미래',
    en:'BIGWAVE3 — The Future of K-Beauty Where Spending Becomes Assets',
    ja:'BIGWAVE3 — 消費が資産になるK-ビューティーの未来',
    zh:'BIGWAVE3 — 消费变资产的K-美妆未来'
  }[lang];
  localStorage.setItem('bw3-lang', lang);
}

document.addEventListener('DOMContentLoaded', () => {
  const sw = document.getElementById('lang-sw');
  const trigger = document.getElementById('lang-trigger');

  // 드롭다운 열기/닫기
  if(trigger) {
    trigger.addEventListener('click', e => {
      e.stopPropagation();
      sw.classList.toggle('open');
    });
  }
  // 외부 클릭 시 닫기
  document.addEventListener('click', () => { if(sw) sw.classList.remove('open'); });

  // 언어 버튼 클릭
  document.querySelectorAll('.lang-btn').forEach(b =>
    b.addEventListener('click', () => {
      setLang(b.dataset.lang);
      if(sw) sw.classList.remove('open');
    }));

  const saved = localStorage.getItem('bw3-lang') || 'ko';
  setLang(saved);
});
